version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corre034_wordpress
      MYSQL_USER: corre034
      MYSQL_PASSWORD: 03Ybr9xPz2
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
