-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 15/08/2018 às 23:36
-- Versão do servidor: 5.6.39-83.1
-- Versão do PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `corre034_wordpress`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `usuario` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `senha` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Nenhum usuário inserido por padrão. Crie via CLI conforme README.
--
-- --------------------------------------------------------

--
-- Estrutura para tabela `vaga`
--

CREATE TABLE `vaga` (
  `titulo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `empresa` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `contato` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descricao` longtext COLLATE utf8_unicode_ci,
  `status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'pendente',
  `id` int(11) NOT NULL,
  `data` date DEFAULT NULL,
  `datavenc` date DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Fazendo dump de dados para tabela `vaga`
--

INSERT INTO `vaga` (`titulo`, `empresa`, `contato`, `descricao`, `status`, `id`, `data`, `datavenc`) VALUES
('Aux Produção', 'Agilidade RH', '(41) 3023-0806', 'Quantidade de vagas: 59 \r\nR$ 1.376,00\r\nEmpresa:.Agilidade Recursos Humanos\r\nLocal de Trabalho:.Paranaguá - PR\r\nDescrição das atividades:.Irá auxiliar no processo de produção da empresa e ensacamento.\r\n\r\nRequisitos:.\r\nExperiência com carga e descarga\r\nCargos operacionais.\r\nResidir em Paranaguá.\r\nEnsino fundamental Completo.\r\n\r\n\r\nDisponibilidade para trabalhar em turnos.\r\nHorário de trabalho:.Disponibilidades de turnos segunda a sexta \r\nRemuneração:.R$ 1.376,00\r\nBenefícios:.Vale Transporte; Alimentação no local\r\n.\r\nInteressados enviar currículo para:. recrutamento03@agilidade.com.br com o assunto \"Auxiliar de Produção - Paranaguá\". \r\nOu preferencialmente se candidatar na vaga no site da Agilidade RH CLICANDO AQUI. https://lnkd.in/dSUqaa4', 'liberado', 123, '2018-07-24', '2018-08-08'),
('Coordenador de Proc. Químicos/Ambientais', 'Kaizen RH', 'www.rhkaizen.com.br', 'Cidade de trabalho: Curitiba /PR\r\nÁrea de atuação Indústria Metal/Mecânica\r\nEscolaridade: Superior Completo em Eng. Ambiental ou Química e formação técnica em Química\r\nHorário de trabalho: Segunda á Sexta-Feira das 07:30 às 17:06\r\n- OBRIGATÓRIA formação no curso de Técnico Químico (Sevá responsável pela empresa junto ao CRQ);\r\n* Experiência em laboratório de indústria metalúrgica;\r\n* Experiência em Iinha de pintura E-COAT\r\n* Deve aceitar ser responsável pela empresa junto ao CRQ, portanto se tiver CRQ ativo será um diferencial, se não tiver, não deverá ter empecilho para a emissão do CRQ.\r\n\r\n* Salário: R$ 6.000,00\r\n* Convênio médico Paraná Clinicas sem mensalidade com coparticipação\r\n* Refeição no Iocal | Seguro de Vida | Convênio Odontológico | Vale Mercado e PPR\r\n\r\nEmail: cintya.santos@rhkaizen.com.br\r\nInteressados, cadastrar currículo  no site da Kaizen www.rhkaizen.com.br\r\n', 'liberado', 178, '2018-07-29', '2018-08-13'),
('Assistente de Logística', 'Louis Dreyfus Company', '(41) 2152- 3600', '01 VAGA ASSISTENTE LOGÍSTICA\r\n\r\nREQUISITOS\r\n~ Superior Completo ou cursando em Logística ou Administração\r\n~ Experiencia com controle de dados\r\n- Conhecimento avançado em Excel\r\n\r\nPRINCIPAIS ATIVIDADES\r\nProgramar carregamentos de operações B2B. Consolidar posição de carregamento versus programação com fornecedores nacionais. Conciliar relatórios de compras nacionais. Elaborar planilha de programação B2B diária.\r\n\r\nBENEFÍCIOS: Convenio Médico; Convenio Odontológico; Seguro de Vida\r\nRefeição na empresa e PPR\r\nLocal de atuação: Paranaguá-PR\r\n\r\nEnvie seu currículo até o dia 30/07/18 para natania.nascimento@ldc.com', 'liberado', 169, '2018-07-27', '2018-08-11'),
('Vendedor', 'MultiLoja', 'gerente059@multiloja.com.br', 'Requisitos:\r\n* Com ou sem experiência\r\n* Acima de 18 anos\r\n* Pro ativa\r\n* Querer aprender\r\n* Se dedicar\r\n* Disponibilidade de horários\r\n\r\nTrazer currículos na MultiLoja de Ipanema ou envie para o email gerente059@multiloja.com.br em PDF.', 'liberado', 170, '2018-07-27', '2018-08-11'),
('Caixa', 'MultiLoja', 'gerente059@multiloja.com.br', 'Requisitos:\r\n* Com ou sem experiência\r\n* Acima de 18 anos\r\n* Pro ativa\r\n* Querer aprender\r\n* Se dedicar\r\n* Disponibilidade de horários\r\n\r\nTrazer currículos na MultiLoja de Ipanema ou envie para o email gerente059@multiloja.com.br em PDF.', 'liberado', 171, '2018-07-27', '2018-08-11'),
('Motorista de carreta', 'Via WhatsApp', '(41)99615-1853', 'Anunciado pelo WhatsApp\r\nEntrar em contato pelo número (41)99615-1853 para maiores informações.', 'liberado', 172, '2018-07-27', '2018-08-11'),
('Servente', 'Via WhatsApp', '(41)99526-2279', 'Anunciado pelo WhatsApp\r\nEntrar em contato pelo telefone (41)99526-2279', 'liberado', 173, '2018-07-27', '2018-08-11'),
('Prof. Cnf Container/Balanceiro', 'Spacio Cursos', '(41)98440-2339', 'Estamos contratando URGENTE!\r\nProfessor para ministrar aulas de Conferente de Container e Balanceiro\r\nInteressados favor realizar o envio do currículo no email: linespacio@hotmail.com\r\nMaiores informações através do Whatsapp (41)98440-2339', 'liberado', 140, '2018-07-25', '2018-08-09'),
('Comprador', 'Aocep', 'edson@aocep.com.br ', 'OPORTUNIDADE PARA PARANAGUÁ - PR.\r\nOportunidade para: Paranaguá-Pr\r\nComprador com Experiencia comprovada, Formação Superior Completo ou em andamento em Logística e ter conhecimento em TOTVS.\r\nAtuação na área portuária corredor de exportação, silo vertical e Az\'s Horizontais.\r\nInteressados enviar e~mail: edson@aocep.com.br com pretensão salarial\r\n', 'liberado', 141, '2018-07-25', '2018-08-09'),
('Assistente de Logística', 'Microfértil', 'https://bit.ly/2LB8tK2', 'Programar carregamentos de operações B2B.\r\nConsolidar posição de carregamento versus programação com fornecedores nacionais.\r\nConciliar relatórios de compras nacionais.\r\nElaborar planilha de programação B2B diária.\r\nSuperior completo ou cursando em Administração ou Logística\r\n\r\nAcesse o site: https://bit.ly/2LB8tK2', 'liberado', 139, '2018-07-25', '2018-08-09'),
('Chapeiro', 'Via Facebook', 'Nayara Takassaki', 'Procurar Nayara Takassaki no Facebook. \r\nAnunciado no Grupo Dani Santiago no Facebook', 'liberado', 136, '2018-07-25', '2018-08-09'),
('Auxiliar de Cozinha', 'Vovó Virginia ', '(41) 3423-1654', '', 'liberado', 137, '2018-07-25', '2018-08-09'),
('Gerente de Desenv. de Negócios', 'Natura', 'https://bit.ly/2A9xOGm', 'Atenção:\r\nA comunicação inicial será feita através do seu e-mail! :)\r\n\r\nVocê é:\r\nComunicativa e com ótimo relacionamento interpessoal;\r\nReceptiva e com facilidade para lidar com diversos públicos;\r\nDeterminada e resiliente para alcançar os objetivos;\r\nInovadora e adora produtos de beleza.\r\n\r\nVocê irá:\r\nOferecer capacitação para Consultores de Beleza Natura e Líderes do seu setor;\r\nOrientar os Líderes, apoiando-os no seu negócio e acompanhar a sua fase inicial;\r\nAnalisar o resultado do setor, por meio da análise dos indicadores constantes dos relatórios disponibilizados pela Natura e da presença nos Encontros Natura;\r\nGerir administrativa e operacionalmente as prestações de conta;\r\nParticipar dos encontros, reuniões e eventuais viagens marcadas pela Natura, para que for convidada ou de que for comunicada;\r\nCadastrar e acompanhar Consultores de Beleza Natura;\r\nOrganizar e implementar os Encontros Natura;\r\nOrganizar e implementar as Reuniões de Ciclo.\r\n\r\n\r\nVocê tem:\r\nFormação Superior Completa;\r\nCarteira de Habilitação e Carro Próprio;\r\nBons conhecimentos em Office;\r\nHabilidade e/ou vivência na área comercial;\r\nDisponibilidade para residir em Paranaguá/PR;\r\n\r\n\r\nDisponibilidade para participar do processo seletivo em Curitiba/PR.\r\nAcesse o site: https://bit.ly/2A9xOGm', 'liberado', 138, '2018-07-25', '2018-08-09'),
('Operador de caixa', 'Cebrac', '(41) 3425-8288', 'Local: Parque Agari\r\nEnsino Médio\r\nDesejável que tenha experiência\r\nDisponibilidade para trabalhar das 15h as 00:00h', 'liberado', 122, '2018-07-24', '2018-08-08'),
('Mecânico', 'Potencial RH', 'https://bit.ly/2AcTZvc', 'Com experiência em máquinas e caminhões', 'liberado', 168, '2018-07-27', '2018-08-11'),
('Auxiliar Adm. e Comercial', 'Marumbit', 'financeiro@marumbit.com.br', 'Auxiliar Adm. e Comercial\r\n\r\nDetalhes do cargo\r\nComo parte dos novos planos de expansão da marumbit estamos selecionando currículos para preencher vagas na área comercial e administratíva. Interessados por favor enviar currículo para o e-mail financeiro@marumbit.com.br\r\nA preferência será para pessoas que moram em Morretes..', 'liberado', 153, '2018-07-26', '2018-08-10'),
('Pedreiro', 'Via Facebook', '(41)996437826', 'Para Pontal do Paraná\r\nLigar no celular (41)996437826', 'liberado', 152, '2018-07-26', '2018-08-10'),
('Empacotador (PCD)', 'SINE', '(41) 3422-3233', 'Médio completo', 'liberado', 150, '2018-07-26', '2018-08-10'),
('Repositor (PCD)', 'SINE', '(41) 3422-3233', 'Médio completo', 'liberado', 151, '2018-07-26', '2018-08-10'),
('Operador de Caixa (PCD)', 'SINE', '(41) 3422-3233', 'Médio completo', 'liberado', 149, '2018-07-26', '2018-08-10'),
('Vendedor (PCD)', 'SINE', '(41) 3422-3233', 'Médio completo', 'liberado', 148, '2018-07-26', '2018-08-10'),
('Doceira', 'SINE', '(41) 3422-3233', 'Doceira com experiência\r\nInteressados deixar currículo no SINE', 'liberado', 147, '2018-07-26', '2018-08-10'),
('Consultor de TI', 'SINE', '(41) 3422-3233', 'Superior cursando em Tecnologia da Informação', 'liberado', 146, '2018-07-26', '2018-08-10'),
('Marceneiro', 'SINE', '(41) 3422-3233', 'Medio completo\r\nExp 3 meses\r\nCNH B', 'liberado', 145, '2018-07-26', '2018-08-10'),
('Encanador industrial', 'SINE', '(41) 3422-3233', 'Superior cursando\r\nExp 3 meses em carteira c/ solda c/ eletrodo\r\nCNH B', 'liberado', 144, '2018-07-26', '2018-08-10'),
('Motorista de caminhão truck', 'SINE', '(41) 3422-3233', 'Medio completo \r\nCNH D ou E\r\nExp 6 meses em carteira com caixa de transferência', 'liberado', 142, '2018-07-26', '2018-08-10'),
('Assistente de TI', 'SINE', '(41) 3422-3233', 'Superior cursando\r\nExp 3 meses em carteira', 'liberado', 143, '2018-07-26', '2018-08-10'),
('Mecânico Locomotivas', 'Vagas.com', 'https://bit.ly/2LVYpYX', 'REQUISITOS:\r\n\r\n• Ensino médio completo;\r\n• Diferencial curso técnico completo ou cursando;\r\n• Conhecimento básico em mecânica;\r\n• Disponibilidade de horários para trabalhar em escala.\r\n\r\nCOMPORTAMENTAL:\r\n\r\n• Responsabilidade;\r\n• Assiduidade;\r\n\r\nATIVIDADES:\r\n\r\n• Auxiliar na manutenção de locomotivas e vagões com montagem e desmontagem de equipamentos mecânicos, como truck, peças móveis mecânicas, alavancas, cilindro de freios e etc.\r\n\r\nLocal de Trabalho: RUMO Logística (Paranaguá - PR)\r\nHorário: 6x2 disponibilidade de horários: 7h às 15h / 15h às 23h / 23h às 07h', 'liberado', 167, '2018-07-27', '2018-08-11'),
('Promotor', 'Vagas.com', 'https://bit.ly/2NRo6u2', 'PARA ATUAR REPRESENTANDO UMA MULTINACIONAL DO RAMO FINANCEIRO, DENTRO DE GRANDES EMPRESAS E INDÚSTRIAS.\r\n\r\nA EMPRESA OFERECE:\r\nSalário: R$ 3.017,35 \r\nBenefícios: VT + VR (R$33,50/dia) \r\nHorário de trabalho: a definir\r\n\r\nATIVIDADES:\r\n\r\nOrganização de kit de aberta de conta; Abertura de conta corrente, conta salário; Apresentação de produtos bancários. \r\n\r\nREQUISITOS:\r\n\r\n\r\nEnsino superior cursando ou completo; Experiência na área bancária. \r\n\r\nVAGA TEMPORÁRIA\r\n\r\nCONSULTORIA DE RECURSOS HUMANOS ESPECIALIZADA EM CONTRATAÇÃO DE MÃO-DE-OBRA TEMPORÁRIA E TERCEIRIZADA', 'liberado', 166, '2018-07-27', '2018-08-11'),
('Profissional de Apoio Téc. Médio II', 'Vagas.com', 'https://bit.ly/2mLbAku', 'Necessário Curso Técnico completo em Meio Ambiente / Segurança do Trabalho / Contabilidade / Administração ou Técnico Industrial, com experiência comprovada na área de atuação e carteira nacional de habilitação categoria B.\r\n\r\nSalário: R$ 2.078,31 + periculosidade, assistência médica/odontológica; seguro de vida; vale-transporte e R$ 27,00 de alimentação por dia.\r\n\r\nLocal de trabalho: Paranaguá/PR.', 'liberado', 165, '2018-07-27', '2018-08-11'),
(' Técnico de Seg. do Trabalho', 'Vagas.com', 'https://bit.ly/2K2j2Rk', 'FORMAÇÃO\r\nFormação completa Técnico de Segurança do Trabalho.\r\n\r\nCONHECIMENTO\r\nPacote Office.\r\nConhecimento nos procedimentos, instruções e normas de Segurança do Trabalho.\r\n\r\nATIVIDADES\r\nAtuar na gestão das atividades da área de segurança, voltada à construção civil.\r\nRealizar treinamentos para atender dos requisitos legais e redução dos riscos de acidente.\r\nSerá responsável por orientar e acompanhar os funcionários quanto às NRs.\r\nAtuar com controle de indicadores, monitoramento de ações e elaboração de documentos de segurança.\r\n\r\nINFORMAÇÕES\r\nDisponibilidade para atuar no Porto de Paranaguá - Paraná, nos próximos 12 meses.\r\n\r\nBENEFÍCIOS: Alojamento, Refeição e Transporte.\r\n\r\nEMPRESA\r\nEmpresa de Sorocaba Prestadora de Serviço Civil em obra no Porto de Paranaguá/Paraná.', 'liberado', 164, '2018-07-27', '2018-08-11'),
('Mecânico', 'Miiller Contabilidade', 'rhmiillercontabiIidade@hotmail.com', 'Os clientes da Miiller Contabilidade estão contratando para a região de Alexandra.\r\n\r\nMecânico com conhecimento e experiência em manutenção e prevenção de maquinas e caminhões\r\n\r\nInteressados enviar curriculum para rhmiillercontabiIidade@hotmail.com', 'liberado', 163, '2018-07-27', '2018-08-11'),
('Assistente de TI', 'Miiller Contabilidade', 'rhmiillercontabiIidade@hotmail.com', 'Os clientes da Miiller Contabilidade estão contratando para a região de Alexandra.\r\n\r\nAssistente de T.I., com conhecimento em\r\n> Conhecimento intermediário de Windows 10, Windows Server 2012 e 2016. AD, DNS, DHCP, Radius. Wifi Corporativo, infraestrutura de Rede, Switches Gerencias, Banco de dados.\r\n> Conhecimento básico em SQL. Postgres e Office 365\r\n> Atendimento ao usuário\r\n\r\nInteressados enviar curriculum para rhmiillercontabiIidade@hotmail.com', 'liberado', 162, '2018-07-27', '2018-08-11'),
('Consultor de Vendas', 'Unimed', 'rh@unimedparanagua.com.br', 'Externo\r\n01 vaga - Paranaguá', 'liberado', 161, '2018-07-27', '2018-08-11'),
('Promotor de Vendas', 'Oniz Distribuidora', 'rh.oniz.com.br', 'A Oniz Distribuidora de Produtos de Higiene e Limpeza  de marcas mundialmente reconhecidas esta com vagas para PROMOTORES DE VENDAS para as seguintes localidades:\r\n- Curitiba\r\n- Pinhais\r\n- Colombo\r\n- Campo Largo\r\n- Almirante Tamandaré/Itaperuçu\r\n- Quitandinha\r\n- Ponta Grossa\r\n- Irati\r\n- Telêmaco Borba\r\n- Jaguariaiva\r\n- Prudentópolis\r\n- Guaratuba\r\n- Paranaguá\r\n- Palmeira/São Mateus do Sul\r\n\r\nRequisitos: Ensino Medio Completo, preferencialmente que já tenha atuado na área e que more próximo às regiões citadas.\r\n\r\nInteressados devem fazer seu cadastro no site rh.oniz.com.br e encaminhar o Curriculum para o email r\r\nrh.sjp2@oniz.com.br informando no assunto: Promotor de Vendas + cidade', 'liberado', 160, '2018-07-27', '2018-08-11'),
('Coordenador de Cursos', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Oportunidade de vaga para Coordenação de Cursos do CEBRAC. ', 'liberado', 176, '2018-07-28', '2018-08-12'),
('Motorista', 'Viação Graciosa', '(41) 3423-1929', 'VAGAS EM ABERTO\r\nATENÇÃO! AS VAGAS SÃO PREFERENCIALMENTE PARA PCD\r\n\r\nMOTORISTA (GERAL)\r\nPara as Cidades de Curitiba, Paranaguá, Antonina, Morretes, Guaratuba, Matinhos, Pontal do Paraná, Joinville e São Francisco do Sul Requisitos: experiência miníma de 3 anos na condução de ônibus ou caminhão de grande porte, Categoria de Habilitação \"D\" ou \"E\", curso de capacitação de transporte coletivo, idade mínima de 28 anos e Ensino Fundamental Completa\r\n\r\nInteressados devem enviar currículo para o e-mail recrutamento@viacaograciosa.com.br ou\r\nentrega-lo na portaria da empresa.\r\n\r\nCANDIDATOS DO LITORAL DO PARANÁ - Poderão preencher Ficha de Solicitação de Emprego ou ainda entregar seu curriculum nas agencias da Viação Graciosa nas cidades do Litoral do Paraná. Não serão atendidos os candidatos fora do perfil.', 'liberado', 158, '2018-07-27', '2018-08-11'),
('Mecânico Diesel', 'Viação Graciosa', '(41) 3423-1929', 'VAGAS EM ABERTO\r\nATENÇÃO! AS VAGAS SÃO PREFERENCIALMENTE PARA PCD\r\n\r\nMECÂNICO DIESEL\r\nRequisitos: experiencia com mecânica diesel em geral com Volvo, Mercedes e Scania. Sexo masculino, idade miníma de 21 anos e disponibilidade de horários.\r\n\r\nInteressados devem enviar currículo para o e-mail recrutamento@viacaograciosa.com.br ou\r\nentrega-lo na portaria da empresa.\r\n\r\nCANDIDATOS DO LITORAL DO PARANÁ - Poderão preencher Ficha de Solicitação de Emprego ou ainda entregar seu curriculum nas agencias da Viação Graciosa nas cidades do Litoral do Paraná. Não serão atendidos os candidatos fora do perfil.', 'liberado', 157, '2018-07-27', '2018-08-11'),
('Consultor(a) de Vendas', 'Via WhatsApp', ' (41)3425-1842', 'Vaga para Consultor(a) de Vendas\r\nContratação imediata\r\n\r\nOferecemos Fixo, bonificação  e comissão. \r\nGanho total variável entre R$ 1.000,00 e R$ 2.000,00.\r\nExperiência em vendas ou atendimento.\r\n\r\nPerfil:\r\nCurioso para conhecer o cliente, o serviço e as técnicas de vendas.\r\nÉ preciso ter Disciplina, pois deve manter o foco nas ações diárias e no que realmente é importante para alcançar a meta, independente de qualquer coisa.\r\nSer Comunicativo, saber se expressar com clareza, ser articulado de forma objetiva.\r\nSer Criativo para buscar alternativas a fim de chegar ao cliente e propor soluções inovadoras.\r\nCapacidade investigativa entendendo e identificando as dificuldades e necessidades do cliente.\r\nSer Adaptável entendendo e aceitando o nosso segmento e treinamento, além de saber lidar com diferentes tipos de clientes e administrar emoções e frustrações.\r\nTer iniciativa para entrar em ação, buscar resultados, ser otimista e persistente para proporcionar vitalidade no dia-a-dia. “Ser persistente é diferente de ser insistente”\r\n\r\nDescrição das responsabilidades:\r\n- Visitar os clientes; Fechar os contratos; Classificar os contratos; Verificar formas e prazos de pagamento junto aos clientes; Buscar e entrar em contato com novos clientes em potencial, utilizando os mecanismos à sua disposição; Manter um Arquivo organizado das matrículas e preencher os relatórios diários; Estar sempre atento quanto às vagas de mercado, para ajudar na profissão e encaminhamento do nosso aluno ao mercado de trabalho;\r\n\r\nAtuamos no ramo de cursos profissionalizantes e temos cursos de informática, secretariado, administração, contabilidade, Atendente de Farmácia, Operadora de Caixa, Idiomas e muito mais! São mais de 90 opções de cursos. Atendemos clientes de Paranaguá  e região .', 'liberado', 159, '2018-07-27', '2018-08-11'),
('Manobrista', 'Viação Graciosa', '(41) 3423-1929', 'VAGAS EM ABERTO\r\nATENÇÃO! AS VAGAS SÃO PREFERENCIALMENTE PARA PCD\r\n\r\nMANOBRISTA\r\nRequisitos: experiencia como manobrista com ônibus e caminhões. Sexo masculino, idade mínima de 28 anos, Categoria de Habilitação \"D\" ou \"E\" e disponibilidade de horários.\r\n\r\nInteressados devem enviar currículo para o e-mail recrutamento@viacaograciosa.com.br ou\r\nentrega-lo na portaria da empresa.\r\n\r\nCANDIDATOS DO LITORAL DO PARANÁ - Poderão preencher Ficha de Solicitação de Emprego ou ainda entregar seu curriculum nas agencias da Viação Graciosa nas cidades do Litoral do Paraná. Não serão atendidos os candidatos fora do perfil.', 'liberado', 155, '2018-07-27', '2018-08-11'),
('Auxiliar FiscoContábil', 'Bonsenhor ', '(41) 2152-2500', 'A Bonsenhor anuncia vaga para a área de FiscoContábil.\r\n\r\nCargo: Auxiliar FiscoContábil\r\nExperiência desejável: 6 meses\r\nFormação: Ensino Médio Completo, preferencialmente cursando superior em Ciências Contábeis e/ou Administração\r\nConhecimento técnico desejável: Triagem e lançamento de despesas, análise e escrituração de notas fiscais (entrada/saída/serviços) e atendimento ao cliente.\r\nHorário de Trabalho: Segunda a sexta-feira das 7:45 às 12:00 e 13:30 às 18:00\r\nBenefícios: Unimed, Dental Uni, Vale Transporte, Vale Alimentação e Auxílio Educação.\r\nConvênios: Sesc, Academia Aquatikus, Farmácia Nissei, Farmácia Popular e Associação dos Funcionários.\r\n\r\nInteressados enviar currículo até dia 02/08 para curriculo@bonsenhor.com.br\r\n\r\nVenha fazer parte deste time!', 'liberado', 154, '2018-07-27', '2018-08-11'),
('Estagiário', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Programa de estágio Cebrac.', 'liberado', 174, '2018-07-28', '2018-08-12'),
('Motorista de Entrega', 'Souza Cruz', 'https://bit.ly/2vcmovS', 'Função: Realizar entregas no varejo, conferência do produto, recebimento de valores, fazer prestação de contas, recolhimento de caixas de papelão.\r\n\r\nPerfil: Pró ativo, organizado, dinâmico, comunicativo\r\n\r\nImprescindível: CNH C, D OU E.\r\nPontuação máxima de 9 pontos na CNH\r\n\r\nTrabalhará com carro da empresa (Fiat Ducato)\r\n\r\nEnsino Médio completo\r\n\r\nHorário de trabalho: segunda a sexta-feira, das 6:00 hrs até terminarem as entregas.\r\n\r\nTrabalha aos sábados eventualmente.\r\n\r\nSalário: R$ 2.402,53 + remuneração variável (R$ 281,00)\r\n\r\nBENEFÍCIOS: VR (27,00/DIA) VA (200,00) VT, Assistência Médica e Odontológica, PNR (15,5 salários anuais), Auxílio Farmácia e Oftalmológico, Plano de Carreira, Celular e outros benefícios.\r\n\r\n*NECESSÁRIO TER DISPONIBILIDADE PARA VIAGENS NO PARANÁ\r\n\r\nFaremos contato somente com os profissionais que estejam estritamente alinhados ao perfil.\r\nOs demais currículos serão salvos em nosso banco para futuras oportunidades.\r\n\r\nTodas as nossas vagas TAMBÉM são disponíveis para Pessoas com Deficiência/PCD', 'liberado', 177, '2018-07-29', '2018-08-13'),
('Camareira ', 'Pousada Favo de Mel', '(41)99991 5909', 'Estamos contratando camareira e cozinheiro ou chef de cozinha, ficamos na Ilha do Mel, litoral do Paraná.\r\nInteressados entrar em contato no whats 99991 5909, favodemelpousada@gmail.com\r\nFalar com Leizor', 'liberado', 190, '2018-07-30', '2018-08-14'),
('Vendedor', 'Lojas Zhuang', '(44)98464-4855', 'Contrata-se vendedor masculino\r\nLevar currículo na loja.', 'liberado', 189, '2018-07-30', '2018-08-14'),
('Supervisor Manutenção Civil', 'Confidencial', 'rh.selecaopgua@gmail.com ', 'OPORTUNIDADE PARA ATUAR EM GRANDE EMPRESA EM PARANAGUÁ-PR.\r\nCargo Descrito: SUPERVISOR DE MANUTENÇÃO CIVIL TR, JR e PL.\r\nEMPRESA:CONFIDENCIAL.\r\nEncaminhar currículos para: rh.selecaopgua@gmail.com \r\n\r\nSumário do Cargo\r\n\r\nPlaneja taticamente a curto e médio prazo, administra recursos, participa ativamente e sugere alteração nos processos de Manutenção Predial. Deve assegurar o cumprimento de todas as normas, procedimentos internos e externos, bem como obedecendo e fazendo cumprir às políticas gerais e de recursos humanos da Empresa.\r\n\r\nResponsabilidades da Área de Atuação\r\n\r\nPLANEJAMENTO E GESTÃO DA MANUTENÇÃO CIVIL\r\nEntender e analisar o escopo de obras civis a serem realizadas por terceiros\r\nRealizar orçamentos e equalização de propostas de fornecedores civis, para apresentar a gerência\r\nFiscalizar a execução das obras enviando relatórios para a gerência\r\nAprovar medições de obras de terceiros\r\nCriar e atualizar plano de manutenção preventivo civil, baseado nas normas da ABNT\r\nAnalisar os índices de eficiência do setor de manutenção civil, e tomar ações corretivas se necessário\r\nDefinir cronograma de manutenção corretiva\r\nRealizar levantamento de quantitativos e solicitar compra de materiais e serviços.\r\n\r\nEncaminhar currículos para: rh.selecaopgua@gmail.com \r\n\r\nRequisitos e Conhecimentos desejáveis\r\n-\r\nTR, JR, PL E SR\r\nEscolaridade	Superior Completo\r\nÁrea de Formação	Engenharia civil ou áreas afins\r\nTempo de Experiência	Acima de 3 anos\r\nConhecimentos Específicos	Pacote Office, Autocad', 'liberado', 219, '2018-07-31', '2018-08-15'),
('Analista ABAP', 'Ritmo Logística', 'recrutamento@ritmolog.com.br', 'AnaIista - ABAP\r\nUnidade Curitiba-PR\r\nRequisitos desejáveis Atividades\r\nSuperior Completo - Engenharia da Computação ou Áreas afins\r\n\r\nProgramação ABAP avançado (SAP ABAP Certified)\r\nDesejável experiência nos Módulos MM, SD, WM\r\n\r\nAtividades:\r\nPrograma, desenvolve e implanta sistemas em linguagem ABAP .\r\nRealiza correções em sistemas para atender às necessidades dos usuários.\r\nDesenvolve trabalhos de montagem, depuração e testes de programas já desenvolvidos.\r\n\r\nINTERESSADOS DEVERÃO ENVIAR CURRÍCULO PARA O E-MAIL: recrutamento@ritmolog.com.br COM O TÍTULO \"ANALISTA ABAP- CURITIBA\"', 'liberado', 220, '2018-08-01', '2018-08-16'),
('Técnico de Edificações', 'Confidencial', 'oportunidades.supermil@gmail.com', 'OPORTUNIDADE PARA MATINHOS - PR.\r\nTécnico em Edificações - Matinhos\r\nVaga de Emprego de Técnico de Edificações\r\nQuantidade de vagas:.01 - R$ a combinar\r\nEmpresa:.Confidencial\r\nLocal de Trabalho:.Matinhos - PR\r\nDescrição das atividades:.Trabalhar na região de Caiobá. Atuar no acompanhamento da execução da obra, realizar relatório fotográfico diário dos serviços realizados, realizar medições dos serviços executados diariamente, realizar medições dos serviços de empreiteiros, elaborar projetos as built, entre outras atividades correlatas ao acompanhamento de obra.\r\n\r\nRequisitos:.Necessário possuir curso técnico em edificações completo, experiência em construção civil, conhecimento a nível intermediário de AutoCad e Pacote Office e disponibilidade para período integral.\r\nHorário de trabalho:.a combinar\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\nInteressados enviar currículo para:. oportunidades.supermil@gmail.com com o título da vaga no assunto.', 'liberado', 243, '2018-08-02', '2018-08-17'),
('Administrativo (Estágio)', 'Confidencial', 'oportunidades.supermil@gmail.com', 'OPORTUNIDADE PARA CAIOBÁ - PR.\r\nEstágio Administrativo em Caiobá\r\nVaga de Estágio Administrativo / Contábil\r\nQuantidade de vagas:.01 - R$ a combinar\r\nEmpresa:.Confidencial\r\nLocal de Trabalho:.Matinhos - PR\r\nDescrição das atividades:.Acompanhar toda rotina administrativa da obra, documentação de funcionários e empreiteiros, registro de cartão ponto, lançamento de NF no sistema, controle de funcionários, planilhas de controles, entre outras atividades pertinentes a área de atuação.\r\n\r\nRequisitos:.Necessário estar cursando graduação em Ciências Contábeis ou Administração, conhecimento a nível intermediário do Pacote Office e disponibilidade para período integral.\r\nHorário de trabalho:.a combinar\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\nInteressados enviar currículo para:. oportunidades.supermil@gmail.com\r\nAviso: ** Colocar sempre o título da vaga no assunto do e-mail.', 'liberado', 242, '2018-08-02', '2018-08-17'),
('Assistente Administrativo', 'Paranaguá Saneamento', 'selecao.paranaguasaneamento@iguasa.com.br', 'OPORTUNIDADE PARA PARANAGUÁ - PR.\r\nAssistente de Engenharia - Paranaguá\r\nVaga de Emprego de Assistente de Engenharia\r\nQuantidade de vagas:.01 - R$ a combinar\r\nEmpresa:.Iguá Saneamento\r\nLocal de Trabalho:.Paranaguá - PR\r\nDescrição das atividades:.Coletar informações sobre inspeções de campo; Auxiliar no controle de suprimentos e almoxarifado de obras; Auxiliar no controle de custos; Interpretar projetos de engenharia; Garantir o registro periódico informações das obras fornecidas pelos Fiscais de campo; Auxiliar na elaboração de relatórios e planilhas; Auxiliar no monitoramento e documentações gerais das obras; \r\nRequisitos:.Ensino médio; Desejável cursando Engenharia. \r\nHorário de trabalho:.a combinar\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\nInteressados enviar currículo para:. selecao.paranaguasaneamento@iguasa.com.br\r\nAviso: ** Colocar sempre o título da vaga no assunto do e-mail.', 'liberado', 241, '2018-08-02', '2018-08-17'),
('Segurança Trabalho Jr', 'Pavi', 'sthefany.domingos@pavi.com.br', 'OPORTUNIDADE PARA PARANAGUÁ - PR.\r\nPRECISA-SE\r\nTECNICO DE SEGURANÇA NO TRABALHO JR\r\n\r\nREQUISITOS:\r\nFormação completa Técnico de Segurança do Trabalho.\r\nDisponibilidade para trabalhar aos sábados.\r\nCNH: B\r\nPacote Office.\r\nConhecimento nos procedimentos, instruções e normas de Segurança do Trabalho.\r\n\r\nATIVIDADES:\r\nAtuar na gestão das atividades da área de segurança.\r\nRealizar treinamentos para atender dos requisitos legais e redução dos riscos de acidente.\r\nSerá responsável por orientar e acompanhar os funcionários quanto às NRs.\r\nCipa\r\nControle e entrega de Epi’s.\r\n\r\nINTERESSADOS ENVIAR CURRÍCULO ATÉ 15/08/2018 NO EMAIL:\r\nSTHEFANY.DOMINGOS@PAVI.COM.BR', 'liberado', 240, '2018-08-02', '2018-08-17'),
('Almoxarife ', 'Grupo Itaete', 'talentos@grupoitaete.com.br', 'Buscamos um novo Almoxarife para integrar nossa equipe:\r\nRequisitos: curso  técnico em logística e pacote office avançado.\r\nAtividades: receber, conferir e despachar materiais; organizar e controlar o estoque; controlar a retirada de materiais a serem utilizados; experiência em arquivo, estoque e almoxarifado. Desejável experiência em estoque de peças, materiais e equipamentos.\r\nLocal de trabalho: Paranaguá-PR\r\nInteressados encaminhar CV com a pretensão salarial para: talentos@grupoitaete.com.br', 'liberado', 261, '2018-08-06', '2018-08-21'),
('Salgadeira', 'Via WhatsApp', '(41)98461-5988', 'Para trabalhar em lanchonete.\r\nMaiores informações pelo (41)98461-5988', 'liberado', 251, '2018-08-05', '2018-08-20'),
('Caixa', 'Brimo\'s Estação Mall', 'contato@brimoscozinhaarabe.com.br', 'Vaga para Caixa com experiência no Brimo\'s Estação Mall\r\nSalário + VT + VA (8hrs por dia)', 'liberado', 252, '2018-08-05', '2018-08-20'),
('Barbeiro', 'Via WhatsApp', '(41)9133-5754', 'Entrar em contato pelo WhatsApp pelo celular (41)9133-5754', 'liberado', 253, '2018-08-05', '2018-08-20'),
('Cabeleireira', 'Via WhatsApp', '(41)9133-5754', 'Entrar em contato pelo WhatsApp pelo celular (41)9133-5754', 'liberado', 254, '2018-08-05', '2018-08-20'),
('Repositor', 'Via Facebook', '(41) 3424-1705', 'Vagas em aberto para 02 lojas Asa Branca\r\nEntregar currículo na loja Santos Dumont. \r\nTelefone: (41) 3424-1705\r\n', 'liberado', 259, '2018-08-06', '2018-08-21'),
('Eletromecânico', 'Paranaguá Saneamento', '0800 605 8115', 'OPORTUNIDADE PARA PARANAGUÁ - PR.\r\nEletromecânico: Paranaguá\r\nVaga de Emprego de Eletromecânico\r\nQuantidade de vagas:.01 - R$ a combinar\r\nEmpresa:.Paranaguá Saneamento\r\nLocal de Trabalho:.Paranaguá - PR\r\n\r\nDescrição das atividades:.\r\n\r\nLeitura e interpretação de desenho N2\r\nLeitura e interpretação de diagramas elétricos, pneumáticos e de automação.\r\nAbertura e fechamento de ordem de serviço (engeman, SAP ou One Word)\r\nReceber do encarregado os serviços a serem executados, discutindo detalhes e necessidade de material utilizado.\r\nEfetuar instalações elétricas e reparos em baixa tensão (até 1000V)\r\nEfetuar instalações elétricas e reparos em alta tensão (acima de 1000V)\r\nEfetuar reparos de equipamentos elétricos desacoplados do sistema de produção (fora de operação)\r\nEfetuar reparos de equipamentos elétricos em carga ou em operação • Adequações elétricas e melhorias\r\nFiscalizar e orientar os terceiros na realização das atividades relacionadas com eletricidade\r\nDesenhar esquemas elétricos\r\nIluminar frentes de serviços, alterando a posição de refletores, fios, tubulações e chaves, observando às normas de segurança exigidos para cada ambiente de trabalho\r\nDirigir Veículos leves\r\nRealizar a manutenção elétrica e mecânica preventiva e corretiva em máquinas, equipamentos, instalações de produção e predial da empresa, de forma a mantê-los em perfeitas condições de uso.\r\nRequisitos:.Informática intermediaria. \r\nFormação técnica em órgão de classe reconhecido (SENAI/CEFET/UFPR). \r\nCarteira de Habilitação B \r\nHorário de trabalho:.a combinar\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\nInteressados enviar currículo para:. selecao.paranaguasaneamento@iguasa.com.br com o título da vaga no assunto', 'liberado', 260, '2018-08-06', '2018-08-21'),
('Auxiliar de Cozinha', 'Via WhatsApp', '(41) 3458-3275', 'Auxiliar de cozinha e açougueiro\r\nMatinhos, PR\r\nContrata- se auxiliar de cozinha e açougueiro! Interessados comparecer na rua Rio Branco n\r\n254 ( Mercado Paglia) praia mansa, no período da manhã das 8 às 11! Salário e horário a\r\ncombinar', 'liberado', 256, '2018-08-06', '2018-08-21'),
('Açougueiro', 'Via WhatsApp', '(41) 3458-3275', 'Auxiliar de cozinha e açougueiro\r\nMatinhos, PR\r\nContrata- se auxiliar de cozinha e açougueiro! Interessados comparecer na rua Rio Branco n\r\n254 ( Mercado Paglia) praia mansa, no período da manhã das 8 às 11! Salário e horário a\r\ncombinar', 'liberado', 257, '2018-08-06', '2018-08-21'),
('Auxiliar de Sushiman', 'Oishi Temakeria', '(41) 3424-2516', 'Ter acima de 18 anos;\r\nMasculino e feminino\r\nDisponibilidade de horário\r\n\r\nInteressados deixar currículo com foto na Av. Bento Munhoz da Rocha Neto, 3606. Parque São João. Anexo ao posto Bortoli.', 'liberado', 258, '2018-08-06', '2018-08-21'),
('Balconista', 'Via WhatsApp', '(41)99816-5641', 'Entrar em contato pelo WhatsApp pelo celular (41)99816-5641', 'liberado', 255, '2018-08-06', '2018-08-21'),
('Aux Administrativo', 'Emprega Brasilia', 'https://bit.ly/2A67CfB', 'Atividades: Suporte administrativo e técnico nas áreas de recursos humanos, administração, finanças e logística. Controlar recebimentos e remessas de correspondências e documentos, atendimento telefônico, assistência na logística da empresa e compras de insumos, preparar documentos (malote), vivência em rotinas departamento pessoal, manter organizados arquivos e cadastros da empresa. Horário de trabalho: segunda a quinta das 07 as 17h e sexta das 07 as 16h com 1h de intervalo.\r\n\r\nNecessário conhecimentos pacote office e experiência na função.\r\n\r\nSalários: R$ 1.750,00.\r\nBenefícios: Vale transporte, Vale alimentação e Seguro de vida.\r\nAcessar o site: https://bit.ly/2A67CfB', 'liberado', 124, '2018-07-24', '2018-08-08'),
('Auxiliar de Cozinha', 'Dolci & Pani', 'contato@dolciepani.com.br', 'VAGA: AUXILIAR DE COZINHA\r\nQuantidade de vagas:.01 \r\nR$ a combinar\r\nEmpresa:.Dolci e Pani \r\nLocal de Trabalho:.Paranaguá - PR\r\n\r\nDescrição das atividades:.Este profissional exerce a função de apoio nas diversas atividades da cozinha como: preparar os ingredientes, porcionar corretamente, auxiliar o cozinheiro no preparo dos pratos. Higienizar a louça e talheres. Zelar pela higiene e segurança alimentar no ambiente de trabalho.\r\n\r\nRequisitos:.Desejável experiência como auxiliar de cozinha\r\nHorário de trabalho:.Integral\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\n\r\nInteressados enviar currículo para:. contato@dolciepani.com.br com o título da vaga no assunto.\r\nOu deixar pessoalmente no local, na loja Dolci e Pani no Shopping Estação Mall', 'liberado', 125, '2018-07-24', '2018-08-08'),
('Aux Confeitaria', 'Dolci & Pani', 'contato@dolciepani.com.br', 'VAGA: AUXILIAR DE CONFEITARIA.\r\nQuantidade de vagas:.01 \r\nR$ a combinar\r\nEmpresa:.Dolci e Pani\r\nLocal de Trabalho:.Paranaguá - PR\r\n\r\nDescrição das atividades:.Atuar como Auxiliar de confeitaria, auxiliando em atividades específicas da função. Preparo do ambiente, separar ingredientes, preparar receitas segundo a orientação do confeiteiro(a), limpas os locais de manipulação de alimentos, higienizar o local de trabalho.\r\n\r\nRequisitos:.Experiência na função. Residir em Paranaguá.\r\nHorário de trabalho:.a combinar\r\nRemuneração:.a combinar\r\nBenefícios:.a combinar\r\n.\r\nInteressados enviar currículo para:. contato@dolciepani.com.br\r\nAviso:  ** Colocar sempre o título da vaga no assunto do e-mail.', 'liberado', 126, '2018-07-24', '2018-08-08'),
('Nutricionista', 'Pró Eventos', '(41) 9111-0035', 'Atividades: Elaborar Manual de boas práticas e cardápios. contratação e treinamento\r\nde equipe. Executar as atividades relativas à promoção de saúde nutricional dos\r\nfuncionários, prever, organizar e controlar os materiais necessários ao desempenho\r\nda cozinha, supervisionar a produção, instalações físicas, e demais funções do\r\ncargo.\r\nSalário= R$ 2.500,00 em CTPS + R$ 500,00 auxílio + alimentação no Iocal\r\nlocal= Paranaguá - PR\r\nHorario=08:00 às 18:00 com 1 hora de intervalo\r\nlnteressadas: Enviar CV através do WhalsApp (41) 9111-0035 ou para recrutamento1@agenciaproeventos.com.br\r\n\r\n', 'liberado', 127, '2018-07-24', '2018-08-08'),
('Técnico Mecânico', 'Rumo Logistica', '(41) 3721-2300', 'Técnico Mecânico\r\nEspecializado - Paranaguá-PR - 4 vagas\r\nTarefas principais:\r\nAuxiliar na estratégia de manutenção;\r\nPré-diagnóstico do vagão;\r\nInspeção direcionada, avaliar quais atividades\r\nprecisam ser realizadas e direcionar ao Iíder.\r\nExecutar atividades de manutenção\r\nRequisitos:\r\nJá tenha trabalhado com responsabilidade de entrega\r\nno último emprego.\r\nEmenda sobre processos de manutenção\r\nConceitos de produtívidade, manutenção mínima.\r\nDiferencia|: Trabalhado com locomotivas. Vagões, outra ferrovia.\r\nExperiencia com ferrovia. Se não, trabalhado como mecânico industrial grandes plantas, pIantas de produção.\r\nPericulosidade 30%', 'liberado', 128, '2018-07-24', '2018-08-08'),
('Soldador I', 'Rumo Logistica', '(41) 3721-2300', 'Soldador I - Paranaguá- PR\r\n\r\nREQUISITOS:\r\n- Ensino médio completo;\r\n- Diferencial curso de solda;\r\n- Conhecimento de processos de soIda;\r\n- Disponibilidade de horários para trabalhar em escala.\r\n\r\nCOMPORTAMENTAL:\r\n- Responsabilidade;\r\n- Assiduidade.\r\nATIVIDADES:\r\n- UtiIização de soIda, eletrodo e MIG;\r\n- ReaIizar solda em partes externas de vagões e\r\nIocomotivas;\r\nLocal de Trabalho: RUMO Logística (Paranaguá - PR)\r\nHorárioz 6x2 disponibilídade de horários: 7h às15h/ 15h às 23h / 23h às 07h', 'liberado', 129, '2018-07-24', '2018-08-08'),
('Mecânico', 'Rumo Logistica', '(41) 3721-2300', 'Mecânico - Paranaguá -PR\r\n\r\nREQUISITOS:\r\n- Ensino médio completo;\r\n- Diferencial curso técnico completo ou cursando;\r\n- Conhecimento básico em mecânica;\r\n- Disponibilidade de horários para trabalhar em escala.\r\n\r\nCOMPORTAMENTAL:\r\n- Responsabilidade;\r\n- Assiduidade;\r\nATIVIDADES:\r\n- Auxíliar na manutenção de Iocomotivas e vagões\r\ncom montagem e desmontagem de equipamentos\r\nmecânicos, como truck, peças móveis mecânicas,\r\nalavancas, cilindro de freios e etc\r\nLocal de Trabalh03 RUMO Logística (Paranaguá - PR)\r\nHorário: 6x2 disponibilidade de horários: 7h às15h/ 15h às 23h / 23h às 07h', 'liberado', 130, '2018-07-24', '2018-08-08'),
('Cabelereiro', 'Syl Shopping Mall', '(41) 3722-3614', 'Contrata-se cabeleireiro com experiência no ramo e manicures. \r\nProcurar a loja Syl no Shopping Mall', 'liberado', 131, '2018-07-24', '2018-08-08'),
('Vendedor Interno', 'Cebrac', 'empregos@cebracparanagua.com.br', 'O Cebrac esta CONTRATANDO uma pessoa para vaga de VENDEDOR INTERNO.\r\nEsta buscando oportunidade na área de VENDAS.\r\nPara você que envio seu CV para o Cebrac a mais de 3 meses, favor enviar novamente para\r\ntermos as informações atualizadas e o email é empregos@cebracparanagua.com.br.\r\nEstamos em busca de uma pessoa inspiradora, motivada e muito comunicativa.\r\n\r\nFaça parte de uma equipe vencedora.\r\nSalário fixo de R$ 1250,00 + comissões (estímativa média de 600,00) + VR (15,00 por dia) + VT.\r\nLembrando, quando envíar o emaíl favor colocar o nome da vaga pretendida no título.\r\n\r\n', 'liberado', 132, '2018-07-24', '2018-08-08'),
('Doméstica', 'SINE', '(41) 3422-3233', 'EXP. 6 MESES/ TER DISPONIBILIDADE PARA CUIDAR DE IDOSO/ TER DISPONIBILIDADE DE HORÁRIO', 'liberado', 133, '2018-07-24', '2018-08-08'),
('Atendente de quiosque', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ EXP. 3 MESES EM ATENDIMENTO AO PÚBLICO', 'liberado', 134, '2018-07-24', '2018-08-08'),
('Zelador de edifício', 'SINE', '(41) 3422-3233', 'FUNDAMENTAL COMPLETO/ QUERER MORAR E TRABALHAR EM PRAIA DE LESTE', 'liberado', 135, '2018-07-24', '2018-08-08'),
('Estágio Administração', 'DENTRAN', '(41)3361-1212', 'Atividades:\r\nAuxiliar no atendimento e informações ao público diverso. Operar equipamentos de comunicação. Digitar, ordenar, encaminhar e arquivar processos e correspondências. Auxiliar nas atividades da área e outras atividades correlatas.\r\n\r\nAcessar: https://bit.ly/2mQggp5', 'liberado', 179, '2018-07-29', '2018-08-13'),
('Estágio Medicina Trabalho', 'APPA', '(41)3420-1161', 'Atividades:\r\nAuxiliar nas atividades diárias da área de segurança do trabalho; auxiliar no arquivamento e entrega de processos; auxiliar nas demais demandas do setor de segurança do trabalho.\r\n\r\nAcessar: https://bit.ly/2Ahwy41', 'liberado', 182, '2018-07-29', '2018-08-13'),
('Estágio Informática', 'APPA', '(41)3420-1161', 'Atividades:\r\nAuxilio no suporte técnico, no atendimento, nas reuniões, manutenção de computadores e auxilio nas demais atividades da área.\r\n\r\nAcessar: https://bit.ly/2LA5KB9', 'liberado', 181, '2018-07-29', '2018-08-13'),
('Estágio DIRAMB', 'APPA', '(41)3420-1161', 'Atividades:\r\nAtendimento ao público, elaboração de relatórios técnicos, fazer pesquisas sobre projetos de gestão ambiental e unidades de conservação, organizar programas de pesquisa ambiental e outras atividades do setor.\r\n\r\nAcessar: https://bit.ly/2LNdMpu', 'liberado', 183, '2018-07-29', '2018-08-13'),
('Motorista de Entrega', 'Zoqbi RH', 'vagas.com.br/v1737786', 'POR FAVOR LEIA COM ATENÇÃO:\r\n\r\n1. A vaga é para ambos os sexos;\r\n2. Inscrições APENAS pelo site VAGAS.COM.BR\r\nAqui ==> vagas.com.br/v1737786\r\n3. NÃO recebemos CV por email, NEM na portaria;\r\n4. NÃO deixe telefone aqui, NÃO vamos ligar;\r\n5. Inscrições até dia 15.08\r\n\r\nFunção: Realizar entregas no varejo, conferência do produto, recebimento de valores, fazer prestação de contas, recolhimento de caixas de papelão.\r\n\r\nPerfil: Pró ativo, organizado, dinâmico, comunicativo\r\n\r\nImprescindível: CNH C, D OU E.\r\nPontuação máxima de 9 pontos na CNH\r\n\r\nTrabalhará com carro da empresa (Fiat Ducato)\r\n\r\nEnsino Médio completo\r\n\r\nHorário de trabalho: segunda a sexta-feira, das 7:00 hrs até terminarem as entregas.\r\n\r\nTrabalha aos sábados eventualmente.\r\n\r\nSalário: R$ 2.402,53 + remuneração variável (R$ 281,00)\r\n\r\nBENEFÍCIOS: VR (27,00/DIA) VA (200,00) VT, Assistência Médica e Odontológica, PNR (15,5 salários anuais), Auxílio Farmácia e Oftalmológico, Plano de Carreira, Celular e outros benefícios.\r\n\r\n*NECESSÁRIO TER DISPONIBILIDADE PARA VIAGENS NO PARANÁ\r\n\r\nFaremos contato somente com os profissionais que estejam estritamente alinhados ao perfil.\r\nOs demais currículos serão salvos em nosso banco para futuras oportunidades.\r\n\r\nTodas as nossas vagas TAMBÉM são disponíveis para Pessoas com Deficiência/PC', 'liberado', 184, '2018-07-29', '2018-08-13'),
('Assistente de Operação', 'Keeper RH', 'dp.pgua@rhkeeper.com.br', 'Contrata-se: Assistente de Operação com experiência (Sistema KMM)\r\nEnviar curriculum: dp.pgua@rhkeeper.com.br\r\nContato apenas por e-mail.', 'liberado', 185, '2018-07-29', '2018-08-13'),
('Técn. de Ensino Metalmecânica/Eletromecânica', 'Senai', 'https://bit.ly/2LZXhn1', 'ATIVIDADES: \r\nElaborar, planejar e ministrar aulas teóricas e práticas na metodologia Senai de Educação Profissional na área de eletromecânica.\r\n\r\nREQUISITOS:\r\nEnsino Superior Completo \r\nDesejável Técnico em Mecânica, Eletromecânica, Engenharia Mecânica, Tecnólogo em Manutenção Industrial ou áreas correlatas.\r\nCNH B e disponibilidade para viagens esporádicas\r\nDesejável experiência como docente ou experiência na área industrial com eletromecânica.\r\n\r\n\r\nINFORMAÇÕES:\r\nLocal de Trabalho: Senai – Paranaguá/PR\r\nTipo de contrato: CLT - Intermitente\r\nHorário: À definir\r\nPeríodo de inscrição: 25/07/2018 a 01/08/2018 \r\n\r\nEssa vaga também se destina a pessoas com deficiência (PCD) ou reabilitados(as).\r\n\r\nEste processo seletivo tem validade de 24 meses, podendo ocorrer o aproveitamento de candidatos aprovados em novas oportunidades deste mesmo perfil, seguindo a ordem de classificação.', 'liberado', 186, '2018-07-29', '2018-08-13'),
('Técnico de Ensino (Exatas)', 'Senai', 'https://bit.ly/2NS0KVe', 'ATIVIDADES: \r\nElaborar, planejar e ministrar aulas teóricas e práticas na metodologia Senai de Educação Profissional na área e Gestão com disciplinas de Exatas.\r\n\r\nREQUISITOS:\r\nEnsino Superior Completo relacionado na área de Administração, Contábil, Matemática, Financeira, Engenharia Elétrica ou Mecânica.\r\nCNH B e disponibilidade para viagens esporádicas\r\nDesejável experiência como docente ou experiência na área industrial nas áreas contábeis, financeira e/ou administrativa.\r\n\r\nINFORMAÇÕES:\r\nLocal de Trabalho: Senai – Paranaguá/PR\r\nTipo de contrato: CLT - Intermitente\r\nHorário: À definir\r\nPeríodo de inscrição: 25/07/2018 a 01/08/2018 \r\n\r\nEssa vaga também se destina a pessoas com deficiência (PCD) ou reabilitados(as).\r\n\r\nEste processo seletivo tem validade de 24 meses, podendo ocorrer o aproveitamento de candidatos aprovados em novas oportunidades deste mesmo perfil, seguindo a ordem de classificação.\r\nINSCREVA-SE PARA ESTA OPORTUNIDADE', 'liberado', 187, '2018-07-29', '2018-08-13'),
('Técnico Ensino Seg. Trabalho', 'Senai', 'https://bit.ly/2vhgd9J', 'ATIVIDADES: \r\nElaborar e planejar e ministrar aulas práticas e teóricas na metodologia Senai de Educação Profissional nos cursos técnicos.\r\n\r\nREQUISITOS:\r\nEnsino Superior Completo relacionado à área de Segurança do Trabalho, preferencialmente Automação Industrial, Engenharia Elétrica e Técnico em Segurança do Trabalho ou especialização na área.\r\nCNH B e disponibilidade para viagens esporádicas\r\nDesejável experiência como docente ou na área industrial em Segurança do Trabalho.\r\n\r\n\r\nINFORMAÇÕES:\r\nLocal de Trabalho: Senai – Paranaguá/PR\r\nTipo de contrato: CLT - Intermitente\r\nHorário: À definir\r\nPeríodo de inscrição: 25/07/2018 a 01/08/2018 \r\n\r\nEssa vaga também se destina a pessoas com deficiência (PCD) ou reabilitados(as).\r\n\r\nEste processo seletivo tem validade de 24 meses, podendo ocorrer o aproveitamento de candidatos aprovados em novas oportunidades deste mesmo perfil, seguindo a ordem de classificação.', 'liberado', 188, '2018-07-29', '2018-08-13'),
('Motorista entregador', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ CNH: C, D OU E/ EXP. 3 MESES EM CARTEIRA', 'liberado', 191, '2018-07-30', '2018-08-14'),
('Eletricista industrial', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ EXP. 3 MESES EM CARTEIRA COM CFTV', 'liberado', 192, '2018-07-30', '2018-08-14'),
('Mecânico locomotivas/vagões', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ EXP. 3 MESES EM CARTEIRA/ DISPONIBILIDADE DE HORÁRIOS PARA TRABALHAR EM ESCALA', 'liberado', 193, '2018-07-30', '2018-08-14'),
('Consultor de negócios', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ CNH:A OU B/ TER CARRO OU MOTO/ EXP. 3 MESES', 'liberado', 194, '2018-07-30', '2018-08-14'),
('Eletricista automotivo', 'SINE', '(41) 3422-3233', 'MÉDIO COMPLETO/ EXP. 6 MESES EM CARTEIRA', 'liberado', 195, '2018-07-30', '2018-08-14'),
('Nutricionista', 'SINE', '(41) 3422-3233', 'SUPERIOR COMPLETO/ EXP. 3 MESES/ PREFERENCIALMENTE TER CARRO OU MOTO', 'liberado', 196, '2018-07-30', '2018-08-14'),
('Aux de produção (PCD)', 'SINE', '(41) 3422-3233', 'FUNDAMENTAL COMPLETO', 'liberado', 197, '2018-07-30', '2018-08-14'),
('Aux enfermagem (Estágio)', 'Talentos', 'talentos@talentosbrasil.com.br', 'Vaga para Paranaguá e Pontal do Paraná\r\nCompareça na Talentos para verificar seu cadastro.\r\nRua Rodrigues Alves, 873 – Centro- Paranaguá\r\n\r\nE-mail: talentos@talentosbrasil.com.br\r\nSite: http://www.talentosbrasil.com.br', 'liberado', 198, '2018-07-30', '2018-08-14'),
('Atendente (Estágio)', 'Talentos', 'talentos@talentosbrasil.com.br', 'Compareça na Talentos para verificar seu cadastro.\r\nRua Rodrigues Alves, 873 – Centro- Paranaguá\r\n\r\nE-mail: talentos@talentosbrasil.com.br\r\nSite: http://www.talentosbrasil.com.br', 'liberado', 199, '2018-07-30', '2018-08-14'),
('Marketing/Propaganda (Estágio)', 'Talentos', 'talentos@talentosbrasil.com.br', 'Compareça na Talentos para verificar seu cadastro.\r\nRua Rodrigues Alves, 873 – Centro- Paranaguá\r\n\r\nE-mail: talentos@talentosbrasil.com.br\r\nSite: http://www.talentosbrasil.com.br', 'liberado', 200, '2018-07-30', '2018-08-14'),
('Aux administrativo (Estágio)', 'Talentos', 'talentos@talentosbrasil.com.br', 'Vaga para Matinhos/Paranaguá\r\nCompareça na Talentos para verificar seu cadastro.\r\nRua Rodrigues Alves, 873 – Centro- Paranaguá\r\n\r\nE-mail: talentos@talentosbrasil.com.br\r\nSite: http://www.talentosbrasil.com.br', 'liberado', 201, '2018-07-30', '2018-08-14'),
('Comercial (Estágio)', 'Talentos', 'talentos@talentosbrasil.com.br', 'Compareça na Talentos para verificar seu cadastro.\r\nRua Rodrigues Alves, 873 – Centro- Paranaguá\r\n\r\nE-mail: talentos@talentosbrasil.com.br\r\nSite: http://www.talentosbrasil.com.br', 'liberado', 202, '2018-07-30', '2018-08-14'),
('Vendedor(a)', 'Via WhatsApp', '(41)995259164', 'Somente quem tiver interesse em trabalhar por comissão.\r\nLigar no (41)995259164 para maiores informações.', 'liberado', 203, '2018-07-30', '2018-08-14'),
('Eletricista', 'Proelman', '(41) 3422-2434', 'VAGA ELETRICISTA\r\nRequisitos\r\nCurso de Elétrica\r\nEnsino Médio Completo\r\nConhecimento em CFTV\r\nEntrevistas na Proelman Paranaguá\r\nRua Maneco Viana, 2173\r\n83206-250 Paranaguá, PR, Brasil', 'liberado', 221, '2018-08-01', '2018-08-16'),
('Profissional Apoio Técnico', 'EPC Engenharia', 'https://bit.ly/2Kbkq42', 'Necessário Curso Técnico em Mecânica completo, com experiência comprovada na área, carteira nacional de habilitação categoria B.\r\n\r\nSalário: R$ 2.078,31 + periculosidade, assistência médica/odontológica; seguro de vida; vale-transporte e R$ 27,00 de alimentação por dia.\r\n\r\nLocal de trabalho: Paranaguá/PR.', 'liberado', 217, '2018-07-30', '2018-08-14'),
('Recepcionista (Inglês)', 'TopWay', 'cvparanagua@topwaynet.com.br', 'OPORTUNIDADE PARA PARANAGUÁ - PR.\r\nCompartilhe você também e Ieve essa\r\noportunidade a outras pessoas.\r\nVAGA: RECEPCIONISTA.\r\nURGENTE!\r\nPara você que é comunicativo e consegue falar inglês, mande o seu currículo para\r\ncvparanagua@topwaynet.com.br.', 'liberado', 222, '2018-08-01', '2018-08-16'),
('Saqueiro', 'Potencial RH', '(41)2152-5500', 'Envie seu currículo para comercial@potencialrecursoshumanos.com', 'liberado', 223, '2018-08-01', '2018-08-16'),
('Biqueiro', 'Potencial RH', '(41)2152-5500', 'Envie seu currículo para comercial@potencialrecursoshumanos.com', 'liberado', 224, '2018-08-01', '2018-08-16'),
('Daleiro', 'Potencial RH', '(41)2152-5500', 'Envie seu currículo para comercial@potencialrecursoshumanos.com', 'liberado', 225, '2018-08-01', '2018-08-16');
INSERT INTO `vaga` (`titulo`, `empresa`, `contato`, `descricao`, `status`, `id`, `data`, `datavenc`) VALUES
('Op. de Produção', 'Potencial RH', '(41)2152-5500', 'Envie seu currículo para comercial@potencialrecursoshumanos.com', 'liberado', 226, '2018-08-01', '2018-08-16'),
('Etiquetador', 'Potencial RH', '(41)2152-5500', 'Envie seu currículo para comercial@potencialrecursoshumanos.com', 'liberado', 227, '2018-08-01', '2018-08-16'),
('Engenharia (Estágio)', 'Martini Meat', ' (41) 3420-3200', 'MARTINI MEAT\r\nESTÁGIO DE NÍVEL SUPERIOR - ENGENHARIA\r\n\r\nRequisitos:\r\nCURSANDO ENGENHARIA MECÂNICA, ELÉTRICA OU DE PRODUÇÃO\r\n\r\nHorário de Trabalho\r\n- 30 HORAS SEMANAIS DE SEGUNDA A SEXTA (HORÁRIO A COMBINAR)\r\n\r\nBenefícios\r\n- BOLSA AUXILIO R$ 1.000,00\r\n- VT, REFEIÇÃO NO LOCAL E SEGURO DE VIDA\r\n\r\nInteressados deverão enviar o currículo no e-mail: rh@martinimeat.com.br, colocar no título \"Estágio - Engenharia\"\r\n', 'liberado', 228, '2018-08-01', '2018-08-16'),
('Motorista', 'Via WhatsApp', '(41)991943287', 'Estamos contratando motorista categoria D, necessário obter experiência comprovada,curso do mopp, sem vicios.\r\ntrajeto: Paranaguá/Araucária.\r\noferecemos:\r\nregistro em carteira\r\nplano de saúde\r\npericulosidade \r\nvale refeição.\r\nobs: somente com experiência.\r\ncontatos somente por WhatsApp- (41)991943287 - Tratar com Junior', 'liberado', 229, '2018-08-01', '2018-08-16'),
('Assistente de TI', 'WA Contábil', '(41) 3423-2383', 'Formação: Ensino médio completo ou superior completo/cursando, preferencialmente nas áreas de sistemas.\r\nConhecimentos necessários: Manutenção e controle de infra-estrutura de ti, familiaridade na instalação e atualização de sistemas e aplicativos em geral (sistemas de gestão / emissores de nfc-e, nf-e, nfs-e, ctr-e será um diferencial), controle de certificados digitais (e-cpf / e-cnpj, a3 / a1), treinamento na utilização de ferramentas e aplicativos.\r\nHorário de trabalho: 8:00 às 12:00 – 13:30 às 18:18 (segunda à sexta)\r\n\r\n\r\nÁrea de atuação: Instrutor / Monitoria em Informática, Infraestrutura / Redes / Suporte, Técnico em Informática \r\n', 'liberado', 230, '2018-08-01', '2018-08-16'),
('Vendedor', 'MP Móveis', '(41) 3462-4199', 'Interessados deverão levar currículo na loja\r\nPerfil masculino com experiência', 'liberado', 231, '2018-08-01', '2018-08-16'),
('Tecn. Segurança Trabalho', 'Grupo Pavi', 'sthefany.domingos@pavi.com.br', 'REQUISITOS:\r\nFormação completa Técnico de Segurança do Trabalho.\r\nDisponibilidade para trabalhar aos sábados.\r\nCNH: B\r\nPacote Office.\r\nConhecimento nos procedimentos, instruções e normas de Segurança do Trabalho.\r\n\r\nATIVIDADES:\r\nAtuar na gestão das atividades da área de segurança.\r\nRealizar treinamentos para atender dos requisitos legais e redução dos riscos de acidente.\r\nSerá responsável por orientar e acompanhar os funcionários quanto às NRs.\r\nCipa\r\nControle e entrega de Epi’s.\r\n\r\nINTERESSADOS ENVIAR CURRÍCULO ATÉ 15/08/2018 NO EMAIL:\r\nSTHEFANY.DOMINGOS@PAVI.COM.BR', 'liberado', 232, '2018-08-01', '2018-08-16'),
('Garçom', 'Hookah Lounge', '(41)998217182', 'Estamos contratando:\r\n02 vagas para garçom;\r\nVaga somente para homens;\r\nHorário das 19:30h até as 06h;\r\nInteressados chamar somente pelo WhatsApp (41)998217182', 'liberado', 233, '2018-08-01', '2018-08-16'),
('Caseiro/chacareiro', 'Via Facebook', '(41)99101-5335', 'Detalhes do cargo\r\nPreciso de um casal para trabalhar como caseiro/chacareiro em uma chácara/pousada bem grande em Garuva\r\nRegistrado, férias, 13 salário, Iivre de aluguel água e luz.\r\nSOMENTE O HOMEM trabalharia todos os dias. a mulher trabalharia alguns dias como diarista e cozinheira.\r\nTrabalha as vezes no finaI de semana e folga no meio da semana.\r\nSalário de R$1.200,00 para o homem e diária de 80.00 para a mulher.\r\n0 homem precisa ter noção de elétrica/hidráulica e serviços básicos de manutenção.\r\nAs entrevistas serão feitas na Borabora Madeiras dia 30 de julho, na próxima segunda-feira às 14h.\r\nRua Vital Brasil 123. - bairro Estação. Araucária\r\nDúvidas entrar em contato pelo número 9.9101-5335 Obrigado.', 'liberado', 234, '2018-08-01', '2018-08-16'),
('Vendedor', 'Boticario', 'rh@luicomercial.com.br', 'O Boticário é a maior rede de franquias de cosméticos do mundo 6 venha fazer parte do nosso time. Envie o seu currículo para rh@luicomercial.com.br\r\n* Vagas disponíveis para Paranaguá e Litoral\r\nNós acreditamos em momentos mágicos. Se você acredita também, vem transformar a vida das pessoas junto com o Boticário!', 'liberado', 235, '2018-08-01', '2018-08-16'),
('Vendedor Externo', 'SINE', '(41) 3422-3233', 'Medio Completo\r\nExp 3 meses em carteira\r\nCNH A', 'liberado', 236, '2018-08-01', '2018-08-16'),
('Padeiro/Aux Padeiro', 'SINE', '(41) 3422-3233', 'Exp 3 meses em carteira', 'liberado', 237, '2018-08-01', '2018-08-16'),
('Jardineiro', 'SINE', '(41) 3422-3233', 'Fundamental Completo\r\nExp 6 meses em carteira', 'liberado', 238, '2018-08-01', '2018-08-16'),
('Op. Pá Carregadeira', 'SINE', '(41) 3422-3233', 'Exp 3 meses em carteira com fertilizantes\r\nCNH D.\r\nTer disponibilidade para trabalhar em turno.', 'liberado', 239, '2018-08-01', '2018-08-16'),
(' Yard Planner', 'TCP', 'https://bit.ly/2vAa1tM', '* Vaga aberta também para PCD \r\n\r\nRequisitos:\r\nSuperior Completo;\r\nDomínio na ferramenta NAVIS;\r\nConhecimento dos processos operacionais portuários;\r\nConhecimento em nomenclatura padrão de contêineres ISO;\r\nConhecimento em nomenclatura de cargas perigosas  IMO. \r\n\r\nAtividades:\r\nResponsável pelo planejamento das demandas de scaner;\r\nRealizar o sequenciamento das demandas de posicionamento do terminal;\r\nPlanejamento de carga/descarga da ferrovia e preparação das unidades;\r\nPrezar pela acuracidade dos inventários. \r\n\r\nLocal de Trabalho: Paranaguá/PR', 'liberado', 244, '2018-08-02', '2018-08-17'),
('Op. de Empilhadeira Pequeno Porte', 'TCP', 'https://bit.ly/2O70ulz', 'Requisitos: \r\nEnsino Médio Completo\r\nCurso de Operador de Empilhadeira\r\nCNH AB\r\n\r\nOperar empilhadeira de pequeno porte para carga e descarga de mercadoria no armazém;\r\nSeguir instruções de posicionamento emitidas pelo Apontador de Az;\r\nRealizar checklist de condições operacionais do equipamento. \r\n\r\nTer disponibilidade de horário.', 'liberado', 245, '2018-08-02', '2018-08-17'),
('Mecânico', 'TCP', 'https://bit.ly/2n4P0DB', '** Vaga aberta, também, para PCDs ** \r\n\r\nRealizar manutenção preventiva, corretivas e inspeções de equipamentos do terminal.', 'liberado', 246, '2018-08-02', '2018-08-17'),
('Chapeiro', 'Via Facebook', '(41)984444577', 'Masculino\r\nCom experiência para trabalhar no Estação Alfrely\r\nDe quarta a segunda, das 18h as 02h. \r\nIdade entre 18 a 35 anos.', 'liberado', 247, '2018-08-02', '2018-08-17'),
('Inspetor de alunos (PCD)', 'SINE', '(41) 3422-3233', 'Médio completo', 'liberado', 248, '2018-08-02', '2018-08-17'),
('Assistente Comercial', 'RH Keeper', 'dp.pgua@rhkeeper.com.br', 'Entrega de currículo somente pelo e-mail dp.pgua@rhkeeper.com.br', 'liberado', 249, '2018-08-02', '2018-08-17'),
('Operador de caixa', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Ensino médio; desejável que tenha experiência\r\nDisponibilidade para trabalhar das 15h a 00h00\r\nLocal: Parque Agari.\r\nInteressados devem encaminhar currículo para e-mail: empregos@cebracparanagua.com.br com o titulo da vaga no assunto do email. Qualquer duvida, ficamos na Av. Arthur de Abreu, 45, centro. Próximo ao Palácio do Cafe.\r\n', 'liberado', 250, '2018-08-03', '2018-08-18'),
('Embalador', 'Casa das Esfihas', '(41)98519-0451', 'Entrar em contato pelo telefone (41)98519-0451', 'liberado', 262, '2018-08-06', '2018-08-21'),
('Promotor', 'SINE', '(41) 3422-3233', 'Medio completo\r\nExp 3 meses em carteira\r\nTer conhecimento de aparelhos e serviços de telefonia móvel', 'liberado', 263, '2018-08-06', '2018-08-21'),
('Motorista de caminhão', 'SINE', '(41) 3422-3233', 'Fundamental completo\r\nCNH C, D, E ou AE', 'liberado', 264, '2018-08-06', '2018-08-21'),
('Atendente de balcão', 'SINE', '(41) 3422-3233', 'Medio completo\r\nExperiência de 03 meses', 'liberado', 265, '2018-08-06', '2018-08-21'),
('Mecânico de ar condicionado', 'SINE', '(41) 3422-3233', 'Medio completo\r\nExperiência de 03 meses em carteira\r\nCNH B\r\nDisponibilidade para realizar viagens', 'liberado', 266, '2018-08-06', '2018-08-21'),
('Caldereiro', 'SINE', '(41) 3422-3233', 'Fundamental completo\r\nExperiência 06 meses em carteira', 'liberado', 267, '2018-08-06', '2018-08-21'),
('Coordenador Adm Comercial', 'SINE', '(41) 3422-3233', 'Superior cursando em Administração, Marketing ou Gestão de Pessoas\r\nExp 03 meses em carteira\r\nCNH AB\r\nTer veículo próprio.', 'liberado', 268, '2018-08-06', '2018-08-21'),
('Vendedor Externo', 'Distribuidora Nova Geração', 'http://distribuidoranovageracao.com.br/trabalhe-conosco', 'QUER FAZER PARTE DO TIME CAMPEÃO DO MAIOR DISTRIBUIDOR AUTORIZADO DO SUL DO PAÍS?\r\nTRADIÇÃO. CONFIANÇA. SALÁRIO JUSTO E PACOTE DE BENEFÍCIOS.\r\n\r\nExperiência na área de vendas a varejo. Habilidade com vendas. Boa comunicação, dinamismo, relacionamento interpessoal, pontualidade. Avidez por desafios e superação de metas. Irá atuar com vendas diretas de bebidas no litoral do Paraná. Remuneração variável.\r\n\r\nVENDEDOR EXTERNO\r\nMOTORISTA\r\nENTREGADOR\r\n\r\nExperiência de no mínimo 1 ano com caminhão toco de marcha reduzida. Agilidade, organização e proatividade. Irá atuar com entregas e carga e descarga de bebidas no litoral paranaense. CNH A, C, D ou E. \r\n\r\nINTERESSADOS\r\nEnviar currículo para: vagas@distribuidorang.com.br Entrar em contato para agendar entrevista.\r\nTelefone: (41) 3071-3149 ou 3071-3103.\r\nEmpresa localizada na Av. Estrada das Praias Km 2,5. Bairro Jardim Esperança.\r\nhttp://distribuidoranovageracao.com.br/trabalhe-conosco', 'liberado', 269, '2018-08-06', '2018-08-21'),
('Motorista', 'Distribuidora Nova Geração', 'http://distribuidoranovageracao.com.br/trabalhe-conosco', 'QUER FAZER PARTE DO TIME CAMPEÃO DO MAIOR DISTRIBUIDOR AUTORIZADO DO SUL DO PAÍS?\r\nTRADIÇÃO. CONFIANÇA. SALÁRIO JUSTO E PACOTE DE BENEFÍCIOS.\r\n\r\nExperiência na área de vendas a varejo. Habilidade com vendas. Boa comunicação, dinamismo, relacionamento interpessoal, pontualidade. Avidez por desafios e superação de metas. Irá atuar com vendas diretas de bebidas no litoral do Paraná. Remuneração variável.\r\n\r\nVENDEDOR EXTERNO\r\nMOTORISTA\r\nENTREGADOR\r\n\r\nExperiência de no mínimo 1 ano com caminhão toco de marcha reduzida. Agilidade, organização e proatividade. Irá atuar com entregas e carga e descarga de bebidas no litoral paranaense. CNH A, C, D ou E. \r\n\r\nINTERESSADOS\r\nEnviar currículo para: vagas@distribuidorang.com.br Entrar em contato para agendar entrevista.\r\nTelefone: (41) 3071-3149 ou 3071-3103.\r\nEmpresa localizada na Av. Estrada das Praias Km 2,5. Bairro Jardim Esperança.\r\nhttp://distribuidoranovageracao.com.br/trabalhe-conosco', 'liberado', 270, '2018-08-06', '2018-08-21'),
('Entregador', 'Distribuidora Nova Geração', 'http://distribuidoranovageracao.com.br/trabalhe-conosco', 'QUER FAZER PARTE DO TIME CAMPEÃO DO MAIOR DISTRIBUIDOR AUTORIZADO DO SUL DO PAÍS?\r\nTRADIÇÃO. CONFIANÇA. SALÁRIO JUSTO E PACOTE DE BENEFÍCIOS.\r\n\r\nExperiência na área de vendas a varejo. Habilidade com vendas. Boa comunicação, dinamismo, relacionamento interpessoal, pontualidade. Avidez por desafios e superação de metas. Irá atuar com vendas diretas de bebidas no litoral do Paraná. Remuneração variável.\r\n\r\nVENDEDOR EXTERNO\r\nMOTORISTA\r\nENTREGADOR\r\n\r\nExperiência de no mínimo 1 ano com caminhão toco de marcha reduzida. Agilidade, organização e proatividade. Irá atuar com entregas e carga e descarga de bebidas no litoral paranaense. CNH A, C, D ou E. \r\n\r\nINTERESSADOS\r\nEnviar currículo para: vagas@distribuidorang.com.br Entrar em contato para agendar entrevista.\r\nTelefone: (41) 3071-3149 ou 3071-3103.\r\nEmpresa localizada na Av. Estrada das Praias Km 2,5. Bairro Jardim Esperança.\r\nhttp://distribuidoranovageracao.com.br/trabalhe-conosco', 'liberado', 271, '2018-08-06', '2018-08-21'),
('Analista Pós-Venda', 'TCP', 'rh@tcp.com.br', 'Enviar currículo para rh@tcp.com.br', 'liberado', 272, '2018-08-06', '2018-08-21'),
('Analista de TI', 'TCP', 'rh@tcp.com.br', 'Enviar currículo para rh@tcp.com.br', 'liberado', 273, '2018-08-06', '2018-08-21'),
('Yard Planner', 'TCP', 'rh@tcp.com.br', 'Enviar currículo para rh@tcp.com.br', 'liberado', 274, '2018-08-06', '2018-08-21'),
('Auditor Interno', 'TCP', 'rh@tcp.com.br', 'Enviar currículo para rh@tcp.com.br', 'liberado', 275, '2018-08-06', '2018-08-21'),
('Tosador ', 'Pet Shop Miados e Latidos', '(41)3453-6502', 'O Pet Shop miados e latidos abriu vaga para tosador com experiência e que tenha referências ,entrar em contato com Volga e Eliane pelos fones 34536502/996432018.', 'liberado', 276, '2018-08-06', '2018-08-21'),
('Operador de empilhadeira', 'RH Keeper', 'dp.pgua@rhkeeper.com.br', 'Contrata-se Operador de empilhadeira com experiência, curso e habilitação. \r\nObs: entrega de currículo apenas por e-mail dp.pgua@rhkeeper.com.br', 'liberado', 277, '2018-08-07', '2018-08-22'),
('Promoter', 'Via WhatsApp', '(44)98825-4245', 'Preciso de uma mulher, para trabalhar com divulgação da promoção do Candeias, precisa ser maior de idade, ter disponibilidade de horário, ser pró-ativa, ter boa aparecia e comunicação, interessadas me chamar no whats (44)98825-4245,  para mais detalhes, inicio imediato.', 'liberado', 278, '2018-08-08', '2018-08-23'),
('Operador de Telemarketing', 'Confidencial', 'leandrojneri@ig.com.br', 'Operador de Telemarketing - Paranaguá\r\nagosto 07, 2018 Destaque, PARANAGUÁ, Região de Paranaguá, Telemarketing/ Call Center,\r\nEmprego de Televendas\r\n\r\nQuantidade de vagas:.01 - R$ a combinar\r\nEmpresa:.Confidencial\r\nLocal de Trabalho:.Paranaguá - PR\r\nDescrição das atividades:.Trabalhar com vendas de planos de TV por Assinatura.\r\nRequisitos:.Experiencia minima de 12 meses, gostar de trabalhar com metas e possuir habilidade de negociação.\r\nHorário de trabalho:.a combinar\r\nRemuneração:.Salário Fixo + comissão\r\nBenefícios:.VT; VR \r\nInteressados enviar currículo para:. leandrojneri@ig.com.br com o assunto \"CV Televendas\"', 'liberado', 279, '2018-08-08', '2018-08-23'),
('Aux Oficina (Lataria/Pintura)', 'Via WhatsApp', '(41)995209227', 'Oportunidade de emprego\r\nPrecisa-se de preparador de oficina lataria e pintura auto motiva mais informação fone 995209227 excelente oportunidade', 'liberado', 280, '2018-08-08', '2018-08-23'),
('Promotor de Vendas', 'HTMTrade', 'diandra.santoni@htmtrade.com', '-	Abordagem ativa (interna e externa) a clientes para venda de planos, aparelhos e serviços de telefonia móvel, realização de ações de vendas.\r\n-	Lançamento de informações de vendas no APP de controle de vendas, positivação do PDV, relacionamento com vendedores e gerente da loja.\r\n\r\n-	Salário + Remuneração Variável\r\n-	Vale Transporte\r\n-	Vale Alimentação ou Refeição\r\n-	Plano de Saúde e Plano Odontológico\r\n\r\nNecessário:\r\n-	Mais de 18 anos;\r\n-	Ensino médio completo;\r\n-	Pro atividade;\r\n-	Responsabilidade.\r\n\r\nEnviar currículo para: diandra.santoni@htmtrade.com', 'liberado', 281, '2018-08-08', '2018-08-23'),
('Gerente Loja Mat. Construção', 'RHF Talentos', 'cv.rhftalentos@gmail.com', 'GERENTE DE LOJA DE MATERIAIS DE CONSTRUÇÃO\r\nSalário: A combinar Benefícios: À combinar\r\nAtividades: Responsável por toda gestão da loja, fechamento de vendas, controle de estoque, financeiro e comercial.\r\nPré-requisitos: Ensino médio completo e experiência recente comprovada de no mínimo 2 anos como gerente de loja de materiais de construção\r\nLocal: Pontal do Paraná-PR\r\nEnviar currículo para: cv.rhftalentos@gmail.com\r\n* Informar a vaga no título do e-mail.\r\n', 'liberado', 282, '2018-08-08', '2018-08-23'),
('Recepcionista de Festa', 'Via Facebook', 'monika@toke@.com', 'CONTRATA-SE URGÊNTE 3 MOÇAS PARA TRABALHAR\r\nMESSE FINAL DE SEMANA COMO RECEPCIONISTA DE FESTA\r\nDE CASAMENTO.\r\nCACHÊ R$ *150,00 POR PESSOA.\r\nSÁBADO A PARTIR DAS 1*1 HORAS.\r\nNÃO EXIGE EXPERIÊNCIA.\r\nSERÁ FORNECIDO: ROUPA, CALÇADO, MAQUIAGEM E CABELO.\r\n\r\nEnvie curriculo para monika@toke@.com\r\n', 'liberado', 283, '2018-08-08', '2018-08-23'),
('Garçonete/Cumim', 'Canoa Quebrada', '(41) 3473-3524', 'Matinhos: Vaga de emprego. Atenção!!! Restaurante Canoa Quebrada Contrata:\r\nGarçonete e Cumim.\r\nAmbos com experiência. Interessados favor comparecer no endereço abaixo portando curriculum e dados pessoais!\r\nAvenida Atlântica N° 876 - Caioba. Obs: Diga que viu na Página Comunica Matinhos.\r\n', 'liberado', 284, '2018-08-08', '2018-08-23'),
('Atendente', 'Monalisa Lanches', 'Ir pessoalmente', 'Levar currículo na lanchonete, que fica ao lado da Lojas Zhuang, próximo ao Hammud Shopping.', 'liberado', 285, '2018-08-08', '2018-08-23'),
('Coordenador de Operações', 'Grupo Itaete', 'talentos@grupoitaete.com.br', 'Estamos com uma oportunidade de Coordenador de Operações para Paranaguá/PR. É imprescindível residir na região.\r\nSerá responsável por coordenar todo o ambiente operacional, fazer gestão de pessoas, elaborar relatórios internos.\r\nCoordenação direta dos Líderes Operacionais e da equipe de funcionários, ter forte atuação na melhoria dos processos, fazer a gestão, tratando a disponibilidade de equipamentos operacionais e recursos para a execução de todas as atividades, ótimo relacionamento com o cliente, com fornecedores garantindo o atendimento aos clientes externo.\r\nVivência com orçamento, custos e despesas. Excel Avançado.\r\nCurso Superior completo em Engenharia de Produção, Administração e/ou áreas correlatas.\r\nInteressados encaminhar CV com a pretensão salarial para: talentos@grupoitaete.com.br', 'liberado', 290, '2018-08-09', '2018-08-24'),
('Eletricista', 'Randstad', 'https://bit.ly/2vtxwp3', 'ATIVIDADES:\r\n\r\n·         Realizar manutenção corretivo-preventiva em equipamentos de automação e segurança ferroviária;\r\n\r\n·         Analisar e reportar os problemas encontrados em campo\r\n\r\nREQUISITOS:\r\n\r\n·         Ensino médio completo\r\n\r\n·         Desejável Técnico em Mecatrônica, Eletrônica, Eletroeletrônica ou Elétrica\r\n\r\n·         CNH B obrigatória\r\n\r\n\r\nINFORMAÇÕES:\r\n\r\n \r\n\r\n·         Local de Trabalho: Morretes/PR\r\n\r\n·         Horário: escala rotativa 6x2 : 07h às 15h, 15h às 23h,  23h às 07h\r\n\r\nLink para acesso a vaga: https://bit.ly/2vtxwp3', 'liberado', 287, '2018-08-08', '2018-08-23'),
('Técnico mecânico', 'EPC Engenharia', 'https://bit.ly/2MvqzKo', 'Necessário Curso Técnico em Mecânica completo, com experiência em fiscalização de contrato de manutenção; abertura e encerramento de notas e ordens de manutenção e carteira nacional de habilitação categoria B.\r\n\r\nDesejável: Conhecimento do Sistema SAP.\r\n\r\nSalário: R$ 2.078,31 + periculosidade, assistência médica/odontológica; seguro de vida; vale-transporte e R$ 27,00 de alimentação por dia.\r\n\r\nLocal de trabalho: Paranaguá/PR.', 'liberado', 288, '2018-08-08', '2018-08-23'),
('Técnico de Manutenção', 'Louis Dreyfus Company', 'https://bit.ly/2MazKDg', 'CURSO: Eletromecânico\r\n\r\nAtuar nas atividades mecânicas e elétricas, com grandes intervenções mecânicas e pequenos reparos elétricos,\r\n\r\nAnálise, reparo e substituição de motores redutores.\r\n\r\nLigações de motores e lubrificação.\r\n\r\nManutenção preventiva em elevadores e transportadores.', 'liberado', 289, '2018-08-08', '2018-08-23'),
('Coordenador Adm Comercial', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 291, '2018-08-09', '2018-08-24'),
('Tecn Segurança Trabalho', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 292, '2018-08-09', '2018-08-24'),
('Promotor', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 293, '2018-08-09', '2018-08-24'),
('Atendente de balcão', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 294, '2018-08-09', '2018-08-24'),
('Vendedor Externo', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 295, '2018-08-09', '2018-08-24'),
('Assistente de TI', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 296, '2018-08-09', '2018-08-24'),
('Mecânico de ar condicionado', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 297, '2018-08-09', '2018-08-24'),
('Motorista de caminhão', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Interessados devem encaminhar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail.', 'liberado', 298, '2018-08-09', '2018-08-24'),
('Chapeiro', 'Via WhatsApp', '(47) 8476-4863', 'Estou selecionado um rapaz que tenha experiências na chapa,fazer lanche diversos ,porções.\r\nInteressados deixar o contato no meu zap (47) 8476-4863. (Heder)\r\n', 'liberado', 299, '2018-08-09', '2018-08-24'),
('Motoboy', 'Via Facebook', '(41)98481-2021', 'Ligar no número (41)98481-2021.\r\nPara fazer entregas de marmitex na hora do almoço.', 'liberado', 300, '2018-08-09', '2018-08-24'),
('Pesquisador Comercial Externo', 'Cebrac', 'empreqos@cebracparanaqua.com.br', 'Pesquisador Comercial Externo\r\n\r\n♦	Descrição: Estabelecer contato direto com o público para divulgação dos serviços oferecidos. Realizar a prospecção de novos clientes através da aplicação de formulário de pesquisa padrão da unidade;\r\n♦	Requisitos: Ensino Médio, Disponibilidade Para Serviços Externos e que seja Comunicativo. *\r\n♦	Salário fixo R$1270,00 + Comissão (Estimativa R$400,00) + VT + VR\r\n♦	Horário: Seg. a Sex: 09:00 às 18:00, Sáb: 13:00 às 17:00 \r\n\r\nInteressados devem enviar o currículo para empreqos@cebracparanaqua.com.br com o título da vaga no assunto do e-mail.\r\n', 'liberado', 301, '2018-08-09', '2018-08-24'),
('Operador de Armazém', 'Armazém Carnaxide', 'sofia.marquez@multitempo.pt', 'Oportunidade: Operador de Armazém para Carnaxide! É necessário certificado de Empilhador. Full Time (8h- 17h) ou Part-Time (20h-24h). Envie a sua candidatura com a referência \"armazémcarnaxide\" para sofia.marquez@multitempo.pt', 'liberado', 302, '2018-08-10', '2018-08-25'),
('Pintor Industrial', 'MR Eletro Comercial', 'recrutamento.mreletrocomercial@gmail.com', 'VAGA - PINTOR INDUSTRIAL \r\nExperiencia comprovada em carteira \r\ninteressados enviar e-mail para : recrutamento.mreletrocomercial@gmail.com.', 'liberado', 303, '2018-08-10', '2018-08-25'),
('Jovem Aprendiz', 'Rebocadores', 'https://bit.ly/2vSTfWM', 'RESPONSABILIDADES:\r\nDar suporte a tarefas administrativas a gestão da equipe.\r\n\r\nCARGA HORÁRIA:\r\n4H.\r\n\r\nAcesse o link para maior detalhe da vaga: https://bit.ly/2vSTfWM', 'liberado', 304, '2018-08-10', '2018-08-25'),
('Servente Obra', 'Via WhatsApp', '(41)99718-7293', 'Preciso de 4 servente dois pedreiro carpinteiro para um serviço temporário em Paranaguá se alguém souber ligar e falar com o Cleiton (41)99718-7293', 'liberado', 305, '2018-08-10', '2018-08-25'),
('Promotor', 'Via WhatsApp', 'marcia@phrh.com.br', 'VAGAS DE PROMOTOR COM MOTO E COM EXP EM FRIOS. \r\nEnviar currículo para marcia@phrh.com.br', 'liberado', 306, '2018-08-10', '2018-08-25'),
('Vendedor de veículos', 'Servopa Paranaguá', '(41) 3420-4800', 'OPORTUNIDADE DE EMPREGO:\r\nA Volkswagen SERVOPA Paranaguá contrata com urgência:\r\n\r\n• Vendedor de veículos com experiência.\r\n\r\nREQUISITOS BÁSICOS: Conhecimento em vendas comprovada, Ensino médio completo, conhecimento em informática.\r\n\r\nInteressados entregar currículo ao cuidados de nosso setor de RH na Alameda Cel. Elyzio Pereira, 523 - Estradinha, Paranaguá - PR.', 'liberado', 307, '2018-08-10', '2018-08-25'),
('Operador de Gate', 'Potencial RH', '(41) 2152-5500', 'Com experiencia comprovada em carteira de trabalho.\r\n\r\nPara mais informações compareça em nosso escritório.\r\n\r\n', 'liberado', 308, '2018-08-10', '2018-08-25'),
('Eletricista Industrial ', 'Potencial RH', '(41) 2152-5500', 'Temos Vaga para - Eletricista Industrial - com os cursos \r\nNR 10 - NR 35 - NR 33\r\nCom certificado de qualificação como eletricista industrial.\r\nPara mais informações compareça em nosso escritório.\r\n\r\n', 'liberado', 309, '2018-08-10', '2018-08-25'),
('Manobrista', 'Potencial RH', '(41) 2152-5500', 'Temos Vaga para - MANOBRISTA - Com Experiência e Habilitação -B-\r\nPara mais informações compareça em nosso escritório.\r\n\r\n', 'liberado', 310, '2018-08-10', '2018-08-25'),
('Mecânico Industrial', 'Potencial RH', '(41) 2152-5500', 'Temos Vaga para Mecânico industrial com experiência comprovada em carteira de trabalho e com certificado de qualificação de mecânico industrial.\r\nPara mais informações compareça em nosso escritório, ou envie seu curriculum.\r\n\r\n', 'liberado', 311, '2018-08-10', '2018-08-25'),
('Promotor de Venda', 'Oniz', 'rh.oniz.com.br', 'Temos vagas para PROMOTORES DE VENDA para diversas regiões do Paraná. A seleção acontecerá a partir do dia 06/08. Interessados devem fazer o cadastro em nosso site rh.oniz.com.br e em seguida mandar o curriculo atualizado para o e-mail rh.sjp2@oniz.com.br informando no assunto PROMOTOR + CIDADE DESEJADA.', 'liberado', 312, '2018-08-10', '2018-08-25'),
('Diarista', 'Via WhatsApp', '(41)8413-6200', 'Preciso de uma diarista -quinzenal\r\nPago 75 +75 150', 'liberado', 313, '2018-08-11', '2018-08-26'),
('Garçom', 'Via WhatsApp', 'jeanschmidt00@gmail.com ', 'Contrato garçom, barman, atendente de bar, cozinheira, auxiliar de cozinha e caixa todos com experiência p ambos os sexo. Interessados mandar curriculum com foto p/ o e-mail: jeanschmidt00@gmail.com \r\nCURRICULUM SEM FOTO SERÁ DESCARTADO!\r\n\r\nPeríodo Noturno.', 'liberado', 314, '2018-08-13', '2018-08-28'),
('Barman', 'Via WhatsApp', 'jeanschmidt00@gmail.com ', 'Contrato garçom, barman, atendente de bar, cozinheira, auxiliar de cozinha e caixa todos com experiência p ambos os sexo. Interessados mandar curriculum com foto p/ o e-mail: jeanschmidt00@gmail.com \r\nCURRICULUM SEM FOTO SERÁ DESCARTADO!\r\n\r\nPeríodo Noturno.', 'liberado', 315, '2018-08-13', '2018-08-28'),
('Cozinheira', 'Via WhatsApp', 'jeanschmidt00@gmail.com ', 'Contrato garçom, barman, atendente de bar, cozinheira, auxiliar de cozinha e caixa todos com experiência p ambos os sexo. Interessados mandar curriculum com foto p/ o e-mail: jeanschmidt00@gmail.com \r\nCURRICULUM SEM FOTO SERÁ DESCARTADO!\r\n\r\nPeríodo Noturno.', 'liberado', 316, '2018-08-13', '2018-08-28'),
('Auxiliar cozinha', 'Via WhatsApp', 'jeanschmidt00@gmail.com ', 'Contrato garçom, barman, atendente de bar, cozinheira, auxiliar de cozinha e caixa todos com experiência p ambos os sexo. Interessados mandar curriculum com foto p/ o e-mail: jeanschmidt00@gmail.com \r\nCURRICULUM SEM FOTO SERÁ DESCARTADO!\r\n\r\nPeríodo Noturno.', 'liberado', 317, '2018-08-13', '2018-08-28'),
('Operador de caixa', 'Via WhatsApp', 'jeanschmidt00@gmail.com ', 'Contrato garçom, barman, atendente de bar, cozinheira, auxiliar de cozinha e caixa todos com experiência p ambos os sexo. Interessados mandar curriculum com foto p/ o e-mail: jeanschmidt00@gmail.com \r\nCURRICULUM SEM FOTO SERÁ DESCARTADO!\r\n\r\nPeríodo Noturno.', 'liberado', 318, '2018-08-13', '2018-08-28'),
('Vendedor Externo', 'Via WhatsApp', 'saionara@advaurora.com.br', 'Requisitos Necessários: Segundo grau completo ou cursando, conhecimento em informática, ter carro próprio, residir na região de PARANAGUÁ.\r\nBenefícios: A empresa oferece Comissão, Cartão Refeição, Plano de Saúde, Plano Odontológico, Auxílio Escolar, entre outros.\r\nInteressados enviar currículo para saionara@advaurora.com.br\r\n', 'liberado', 319, '2018-08-13', '2018-08-28'),
('Consultor de negócios', 'Cebrac', '(41) 3425-8288', 'Requisitos:\r\nDisponibilidade de Horário - Ser proativo - conhecimento básico informática - boa comunicação e apresentação pessoal - Trabalhar com metas.\r\n\r\nCarga horaria 6 horas , piso salarial do Shopping R$1270,00 + comissão + VL + VR. \r\n\r\nLocal: Estação Mall\r\nInteressados devem Procurar a Agência com o Currículo.\r\nFicamos na Av. Arthur de Abreu, 45 Centro. Ao Lado do Palácio do Café.', 'liberado', 320, '2018-08-13', '2018-08-28'),
('Pasteleira', 'Via WhatsApp', '(41)99586-7152', 'Preciso de uma mulher para trabalhar dois dias por semana para fritar pastel\r\nInteressados devem entrar em contato pelo WhatsApp (41)99586-7152', 'liberado', 321, '2018-08-13', '2018-08-28'),
('Aux Cozinha', 'SINE', '(41) 3422-3233', 'Exp 6 meses em carteira', 'liberado', 322, '2018-08-13', '2018-08-28'),
('Vendedor(a)', 'Maikon Antenas', '(41) 99735-1116', 'MAIKON ANTENAS CONTRATA!\r\n\r\nESTAMOS ACEITANDO CURRICULUM PARA CONTRATAÇÃO DE VENDEDOR (A)\r\n\r\n-Informações só no local\r\n-Levar curriculum\r\n\r\nAvenida Curitiba 170 Bom Retiro- Matinhos', 'liberado', 323, '2018-08-14', '2018-08-29'),
('Eletricista', 'Potencial RH', 'comercial@potencialrecursoshumanos.com', 'Vagas em aberto Potencial RH\r\n\r\nEletricista (com curso, NR10, 33 e 35)\r\nMecanico  (com curso, NR33 e 35)\r\n\r\nEnviar currículo para comercial@potencialrecursoshumanos.com', 'liberado', 324, '2018-08-14', '2018-08-29'),
('Mecânico', 'Potencial RH', 'comercial@potencialrecursoshumanos.com', 'Vagas em aberto Potencial RH\r\n\r\nEletricista (com curso, NR10, 33 e 35)\r\nMecanico  (com curso, NR33 e 35)\r\n\r\nEnviar currículo para comercial@potencialrecursoshumanos.com', 'liberado', 325, '2018-08-14', '2018-08-29'),
('Auxiliar de cozinha', 'Yuu Japanese Food', 'curriculosjapa14@yahoo.com.br', 'Yuu Japanese Food\r\n\r\nContrata-se auxiliar de cozinha para trabalhar no período da noite, interessados enviar currículo para curriculosjapa14@yahoo.com.br!\r\nVenha fazer parte da nossa equipe!!!', 'liberado', 326, '2018-08-14', '2018-08-29'),
('Promotor', 'Via WhatsApp', 'marcia@phrh.com.br', 'VAGAS DE PROMOTOR COM MOTO E COM EXP EM FRIOS. CV marcia@phrh.com.br', 'liberado', 327, '2018-08-14', '2018-08-29'),
('Vendedora', 'Valentine Modas', ' (41) 99910-3038', 'Vendedora de loja (vaga feminina), idade mínima 18 anos, com experiência em vendas;\r\nInteressados comparecer na Rua da fonte, 316 centro, ao lado caixa economica - Matinhos - PR.\r\n- Trazer currículo;\r\n- Salário à combinar; — em Valentine Modas', 'liberado', 328, '2018-08-14', '2018-08-29'),
('Ajudante de entregas', 'Gigroup', 'recepcao.curitiba@gigroup.com', 'AJUDANTE DE ENTREGAS - Com experiência em carga e descarga, movimentação de produtos, conferência de notas fiscais. Ensino Médio Completo; Salário fixo + VT + VR; Disponibilidade de Horário.\r\n\r\nMOTORISTA - Necessário ter experiência como motorista, entrega de produtos, conferência de notas fiscais. CNH D; Ensino Médio Completo; Salário Fixo + VT + VR; Disponibilidade de horário;\r\n\r\nOBS: vaga temporária\r\n\r\nINTERESSADOS ENCAMINHAR CURRÍCULO COM TITULO DA VAGA PARA: recepcao.curitiba@gigroup.com', 'liberado', 329, '2018-08-14', '2018-08-29'),
('Motorista', 'Gigroup', 'recepcao.curitiba@gigroup.com', 'AJUDANTE DE ENTREGAS - Com experiência em carga e descarga, movimentação de produtos, conferência de notas fiscais. Ensino Médio Completo; Salário fixo + VT + VR; Disponibilidade de Horário.\r\n\r\nMOTORISTA - Necessário ter experiência como motorista, entrega de produtos, conferência de notas fiscais. CNH D; Ensino Médio Completo; Salário Fixo + VT + VR; Disponibilidade de horário;\r\n\r\nOBS: vaga temporária\r\n\r\nINTERESSADOS ENCAMINHAR CURRÍCULO COM TITULO DA VAGA PARA: recepcao.curitiba@gigroup.com', 'liberado', 330, '2018-08-14', '2018-08-29'),
('Auxiliar de cozinha', 'Via WhatsApp', 'tatatissot@gmail.com', 'Contrata-se auxiliar de cozinha para trabalhar no período da noite \r\nInteressados enviar currículo para e-mail \r\ntatatissot@gmail.com', 'liberado', 331, '2018-08-14', '2018-08-29'),
('Cuidadora', 'Via Facebook', '(41)98464-5227', 'Para cuidar de um idoso no Hospital Regional\r\nEntrar em contato pelo telef. (41)98464-5227', 'liberado', 332, '2018-08-14', '2018-08-29'),
('Cozinheira', 'Pasta Nostra', '(41) 3425-5252', 'Boa noite, Restaurante Pasta Nostra está contratando cozinheira e auxiliar de cozinha com experiência . Rua:João Eugênio , n° 711 Shopping Estação Mall.\r\nFavor deixar currículo no local acima, à partir das 14hrs até às 18hrs .\r\nGrata Equipe Pasta Nostra .\r\n', 'liberado', 333, '2018-08-14', '2018-08-29'),
('Auxiliar de cozinha', 'Pasta Nostra', '(41) 3425-5252', 'Boa noite, Restaurante Pasta Nostra está contratando cozinheira e auxiliar de cozinha com experiência . Rua:João Eugênio , n° 711 Shopping Estação Mall.\r\nFavor deixar currículo no local acima, à partir das 14hrs até às 18hrs .\r\nGrata Equipe Pasta Nostra .\r\n', 'liberado', 334, '2018-08-14', '2018-08-29'),
('Inspetor de qualidade', 'Employer RH', '(41)3423-1900 ', 'PROCESSO SELETIVO \r\nVAGA: Inspetor de Qualidade CIDADE: Paranaguá/PR CONHECIMENTOS: Word, Excel e Metrologia. Experiência com atividades de inspeção de qualidade em qualquer segmento. \r\nREQUISITOS: Ensino Médio Completo, experiência comprovada em carteira. \r\nBENEFÍCIOS: Assistência médica, odontológica, convênio farmácia, vale alimentação, vale transporte, refeição na empresa, seguro de vida, previdência privada e participação nos resultados. \r\nHORÁRIO: Disponibilidade de horário. \r\nINTERESSADOS: Enviar currículo atualizado para o endereço abaixo: priscilapinheiro@employer.com.br 413423-1900 \r\n', 'liberado', 335, '2018-08-14', '2018-08-29'),
('Cozinheiro de restaurante', 'SINE', '(41) 3422-3233', 'EXP 3 MESES', 'liberado', 336, '2018-08-14', '2018-08-29'),
('Aux Serviços Gerais', 'Potencial RH', 'comercial@potencialrecursoshumanos.com', 'Enviar CV para comercial@potencialrecursoshumanos.com informando a vaga de interesse no campo assunto.', 'liberado', 337, '2018-08-14', '2018-08-29'),
('Balanceiro', 'Potencial RH', 'comercial@potencialrecursoshumanos.com', 'Enviar CV para comercial@potencialrecursoshumanos.com informando a vaga de interesse no campo assunto.', 'liberado', 338, '2018-08-14', '2018-08-29'),
('Técnico de atividades (Recreação)', 'SESC Paranaguá', 'https://www.sescpr.com.br/sesc-parana/trabalhe-conosco/#edital-13523', 'Inscrições e informações pelo site: https://www.sescpr.com.br/sesc-parana/trabalhe-conosco/#edital-13523\r\n\r\nEscolaridade Mínima: Ensino Superior Completo em Educação Física (Bacharel), curso reconhecido e concluído em instituição de ensino superior credenciada pelo MEC.\r\nRequisitos: Carteira de Habilitação Profissional: Registro ativo no CREF\r\nExperiência: 06 meses de experiência comprovada em recreação: organização e realização de eventos recreativos ou acompanhamento e aplicação de atividades recreativas ou organização e aplicação de atividades recreativas para crianças e adultos.\r\nCarga horária: 40h semanais', 'liberado', 339, '2018-08-14', '2018-08-29'),
('Pizzaiolo', 'Chefe Lanches', '(41)99709-3747', 'Entregar currículo com experiência no Chefe Lanches e Restaurante das 11h as 14h.', 'liberado', 340, '2018-08-14', '2018-08-29'),
('Aux de cozinha', 'Chefe Lanches', '(41)99709-3747', 'Entregar currículo com experiência no Chefe Lanches e Restaurante das 11h as 14h.', 'liberado', 341, '2018-08-14', '2018-08-29'),
('Encanador', 'SINE', '(41) 3422-3233', 'MEDIO COMPLETO\r\n6 MESES EM CARTEIRA\r\nCNH A', 'liberado', 342, '2018-08-15', '2018-08-30'),
('Aux Administrativo', 'SINE', '(41) 3422-3233', 'MEDIO COMPLETO\r\nEXP 3 MESES EM CARTEIRA', 'liberado', 343, '2018-08-15', '2018-08-30'),
('Cozinheiro', 'SINE', '(41) 3422-3233', 'EXP 3 MESES EM CARTEIRA', 'liberado', 344, '2018-08-15', '2018-08-30'),
('Auxiliar de costureira', 'Via WhatsApp', '(41)98491-7842', 'Contrata-se auxiliar de costureira c/ experiência interessados entrar em contato para o num 984917842 falar com Geovana(somente ligacao )', 'liberado', 345, '2018-08-15', '2018-08-30'),
('Jovem aprendiz', 'Inat', 'thaline.santos@inat.org.br', 'Oportunidade de emprego jovem aprendiz\r\n\r\nPré-requisitos:\r\n✔Idade - 17 anos\r\n✔Informatica básica\r\n✔Inglês básico\r\n✔Ser comunicativo(a), interessado(a) e pontual.\r\n\r\nEncaminhar currículo para o seguinte e-mail: thaline.santos@inat.org.br', 'liberado', 346, '2018-08-15', '2018-08-30'),
('Apoio Adm Nível Médio', 'Vagas.com', 'https://bit.ly/2Bfsq56', 'Escolaridade: Ensino Médio Completo.\r\n\r\nExperiência comprovada na área administrativa e sólidos conhecimentos em informática.\r\n\r\nSalário: R$ 1.620,00 + benefícios\r\n\r\nLocal de trabalho: Paranaguá/PR\r\n\r\nPrevisão de início: Imediato', 'liberado', 347, '2018-08-15', '2018-08-30'),
('Apoio Técnico Nível Médio II', 'Vagas.com', 'https://bit.ly/2OFvn0K', 'Escolaridade: Curso Técnico Completo em Eletromecânica.\r\n\r\nExperiência comprovada em Planejamento, Manutenção e Montagem.Sólidos conhecimentos em informática.\r\n\r\nNecessário carteira de habilitação categoria B.\r\n\r\nDesejável conhecimento do Sistema SAP.\r\n\r\nSalário: R$ 2.066,54 + benefícios\r\n\r\nLocal de trabalho: Paranaguá/PR\r\n\r\nPrevisão de início: Imediato', 'liberado', 348, '2018-08-15', '2018-08-30'),
('Garçom', 'Via WhatsApp', '(47)98476-4863', 'Estou precisando de um garçom...\r\nChamar no zap por favor.\r\nParanaguá', 'liberado', 349, '2018-08-15', '2018-08-30'),
('Gerente de loja', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Empresa Parceira Contrata\r\n\r\nGerente de Loja\r\n\r\nLocal: Guaratuba\r\n\r\nRequisitos: Desejável superior completo ou Cursando. Experiência em Gestão e conhecimento em Telecom.\r\n\r\nPrincipais Atividades:\r\n\r\n* Gestão dos relatórios gerenciais, bem como conferência dos indicadores com os sistemas oficiais, sempre que disponíveis;\r\n* Garantir, monitorar e alinhar as práticas comerciais e técnicas de vendas nas lojas (exposição de materiais, aparelhos, ofertas, campanhas, apresentação da loja e da equipe de colaboradores)\r\n* Acompanhamento das ações da concorrência na sua área de atuação;\r\n* Promove a realização de reuniões diárias com a equipe antes da abertura da loja (duração média de 15 minutos)\r\n* Implementar ferramentas que promovam a melhoria do atendimento ao cliente pelas avaliações periódicas, mensuráveis e objetivas garantindo um padrão de qualidade e excelência superior ao encontrado no mercado.\r\n* Domínio das técnicas de vendas, atendimento e negociação\r\n\r\nInteressados devem enviar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail', 'liberado', 350, '2018-08-15', '2018-08-30'),
('Vendedor', 'Cebrac', 'empregos@cebracparanagua.com.br', 'Vendedor - Para Trabalhar em Guaratuba\r\n\r\n☑Requisitos:\r\n\r\nSer proativo - conhecimento básico informática - boa comunicação e apresentação pessoal - Trabalhar com metas.\r\n\r\n☑Atividades: Responsável por identificar as necessidades do cliente e ofertar os melhores produtos e serviços, visando encantar o cliente e atingir os resultados quantitativos e qualitativos\r\nEstabelecer relacionamento de confiança com os clientes com o objetivo de fidelizá-los.\r\nSeguir os procedimentos de conferência de documentos garantindo o cumprimento das normas internas e externas.\r\nSuperar as metas individuais em todos os indicadores do negócio.\r\nConhecer o mercado de Telecom e a concorrência.\r\n\r\n☑Horário: Seg. a Sex. 09:00 ás 18:00 Horas e Sábado até ás 15:00\r\n\r\n☑Salário: R$1270,00 + comissão + VL + VR.\r\n\r\n☑Local: Guaratuba\r\n\r\nInteressados devem enviar o currículo para empregos@cebracparanagua.com.br com a vaga no assunto do e-mail', 'liberado', 351, '2018-08-15', '2018-08-30');

--
-- Índices de tabelas apagadas
--

--
-- Índices de tabela `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `vaga`
--
ALTER TABLE `vaga`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas apagadas
--

--
-- AUTO_INCREMENT de tabela `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de tabela `vaga`
--
ALTER TABLE `vaga`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=352;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
